// This file is auto-generated. Do not edit directly.
// Contains phonetic transcriptions for words from your songs, derived from CMUdict.
export const songVocabularyPhoneticMap = {
  "ops": "AA1 P S",
  "pour": "P AO1 R",
  "lid": "L IH1 D",
  "locked": "L AA1 K T",
  "unconventional": "AH2 N K AH0 N V EH1 N SH AH0 N AH0 L",
  "acting": "AE1 K T IH0 NG",
  "iron": "AY1 ER0 N",
  "shone": "SH OW1 N",
  "prevented": "P R IH0 V EH1 N T IH0 D",
  "method": "M EH1 TH AH0 D",
  "connect": "K AH0 N EH1 K T",
  "burn": "B ER1 N",
  "hesitation": "HH EH2 Z AH0 T EY1 SH AH0 N",
  "measured": "M EH1 ZH ER0 D",
  "clap": "K L AE1 P",
  "syndication": "S IH2 N D IH0 K EY1 SH AH0 N",
  "neck": "N EH1 K",
  "door": "D AO1 R",
  "explore": "IH0 K S P L AO1 R",
  "ship": "SH IH1 P",
  "savor": "S EY1 V ER0",
  "exit": "EH1 G Z IH0 T",
  "deformed": "D IH0 F AO1 R M D",
  "disparaged": "D IH0 S P EH1 R IH0 JH D",
  "invocation": "IH2 N V AH0 K EY1 SH AH0 N",
  "erodes": "IH0 R OW1 D Z",
  "hours": "AW1 ER0 Z",
  "sleeping": "S L IY1 P IH0 NG",
  "put": "P UH1 T",
  "wave": "W EY1 V",
  "die": "D AY1",
  "escaping": "IH0 S K EY1 P IH0 NG",
  "sharpen": "SH AA1 R P AH0 N",
  "wary": "W EH1 R IY0",
  "turing": "T UH1 R IH0 NG",
  "safe": "S EY1 F",
  "sacrifice": "S AE1 K R AH0 F AY2 S",
  "maintain": "M EY0 N T EY1 N",
  "freak": "F R IY1 K",
  "beheading": "B IH0 HH EH1 D IH0 NG",
  "commensurate": "K AH0 M EH1 N S ER0 AH0 T",
  "black": "B L AE1 K",
  "foundry": "F AW1 N D R IY0",
  "alive": "AH0 L AY1 V",
  "repeats": "R IH0 P IY1 T S",
  "hear": "HH IY1 R",
  "potential": "P AH0 T EH1 N SH AH0 L",
  "pale": "P EY1 L",
  "matter": "M AE1 T ER0",
  "save": "S EY1 V",
  "seductive": "S IH0 D AH1 K T IH0 V",
  "gods": "G AA1 D Z",
  "infrastructure": "IH2 N F R AH0 S T R AH1 K CH ER0",
  "eat": "IY1 T",
  "bastard": "B AE1 S T ER0 D",
  "hearing": "HH IY1 R IH0 NG",
  "condition": "K AH0 N D IH1 SH AH0 N",
  "bag": "B AE1 G",
  "admonished": "AH0 D M AA1 N IH0 SH T",
  "finally": "F AY1 N AH0 L IY0",
  "rethink": "R IY0 TH IH1 NG K",
  "ground": "G R AW1 N D",
  "oblivion": "AH0 B L IH1 V IY0 AH0 N",
  "sooner": "S UW1 N ER0",
  "ends": "EH1 N D Z",
  "random": "R AE1 N D AH0 M",
  "powers": "P AW1 ER0 Z",
  "plight": "P L AY1 T",
  "eye": "AY1",
  "prepare": "P R IY0 P EH1 R",
  "white": "W AY1 T",
  "soon": "S UW1 N",
  "obscene": "AA0 B S IY1 N",
  "wall": "W AO1 L",
  "populace": "P AA1 P Y AH0 L AH0 S",
  "location": "L OW0 K EY1 SH AH0 N",
  "flavor": "F L EY1 V ER0",
  "twitching": "T W IH1 CH IH0 NG",
  "pain": "P EY1 N",
  "until": "AH0 N T IH1 L",
  "crash": "K R AE1 SH",
  "dilapidated": "D IH0 L AE1 P AH0 D EY2 T IH0 D",
  "guess": "G EH1 S",
  "negative": "N EH1 G AH0 T IH0 V",
  "infant": "IH1 N F AH0 N T",
  "futility": "F Y UW0 T IH1 L AH0 T IY0",
  "ex": "EH1 K S",
  "violence": "V AY1 AH0 L AH0 N S",
  "intersection": "IH2 N T ER0 S EH1 K SH AH0 N",
  "sound": "S AW1 N D",
  "evoked": "IH0 V OW1 K T",
  "opportunity": "AA2 P ER0 T UW1 N AH0 T IY0",
  "structure": "S T R AH1 K CH ER0",
  "humans": "HH Y UW1 M AH0 N Z",
  "late": "L EY1 T",
  "listless": "L IH1 S T L AH0 S",
  "gifted": "G IH1 F T AH0 D",
  "quarter": "K W AO1 R T ER0",
  "remain": "R IH0 M EY1 N",
  "blinded": "B L AY1 N D IH0 D",
  "stations": "S T EY1 SH AH0 N Z",
  "box": "B AA1 K S",
  "financial": "F AH0 N AE1 N SH AH0 L",
  "following": "F AA1 L OW0 IH0 NG",
  "immense": "IH2 M EH1 N S",
  "infused": "IH2 N F Y UW1 Z D",
  "proper": "P R AA1 P ER0",
  "comprehensive": "K AA2 M P R IY0 HH EH1 N S IH0 V",
  "unmanaged": "AH0 N M AE1 N IH0 JH D",
  "tenements": "T EH1 N AH0 M AH0 N T S",
  "senescence": "S AH0 N EH1 S AH0 N S",
  "sunk": "S AH1 NG K",
  "ropes": "R OW1 P S",
  "gather": "G AE1 DH ER0",
  "live": "L AY1 V",
  "worry": "W ER1 IY0",
  "worst": "W ER1 S T",
  "lifted": "L IH1 F T AH0 D",
  "tethered": "T EH1 DH ER0 D",
  "reverse": "R IH0 V ER1 S",
  "invert": "IH2 N V ER1 T",
  "saturated": "S AE1 CH ER0 EY2 T IH0 D",
  "grandeur": "G R AE0 N D UW1 R",
  "took": "T UH1 K",
  "consolidator": "K AH0 N S AA1 L IH0 D EY2 T ER0",
  "errors": "EH1 R ER0 Z",
  "solvent": "S AA1 L V AH0 N T",
  "persons": "P ER1 S AH0 N Z",
  "rogue": "R OW1 G",
  "propels": "P R AH0 P EH1 L Z",
  "met": "M EH1 T",
  "affording": "AH0 F AO1 R D IH0 NG",
  "fallen": "F AA1 L AH0 N",
  "treat": "T R IY1 T",
  "paths": "P AE1 DH Z",
  "relentless": "R IH0 L EH1 N T L IH0 S",
  "placing": "P L EY1 S IH0 NG",
  "topics": "T AA1 P IH0 K S",
  "contemptuous": "K AH0 N T EH1 M P CH UW0 AH0 S",
  "helps": "HH EH1 L P S",
  "reduced": "R IH0 D UW1 S T",
  "force": "F AO1 R S",
  "made": "M EY1 D",
  "quite": "K W AY1 T",
  "hands": "HH AE1 N D Z",
  "infiltrated": "IH1 N F IH0 L T R EY2 T IH0 D",
  "viable": "V AY1 AH0 B AH0 L",
  "laden": "L EY1 D AH0 N",
  "forces": "F AO1 R S IH0 Z",
  "obtained": "AH0 B T EY1 N D",
  "speak": "S P IY1 K",
  "roll": "R OW1 L",
  "seems": "S IY1 M Z",
  "fall": "F AO1 L",
  "lent": "L EH1 N T",
  "recognition": "R EH2 K AH0 G N IH1 SH AH0 N",
  "okay": "OW2 K EY1",
  "bridges": "B R IH1 JH AH0 Z",
  "lower": "L OW1 ER0",
  "insurrection": "IH2 N S ER0 EH1 K SH AH0 N",
  "ragged": "R AE1 G AH0 D",
  "self-righteous": "S EH2 L F R AY1 CH AH0 S",
  "mapped": "M AE1 P T",
  "kiss": "K IH1 S",
  "lovin": "L OW1 V IH0 N",
  "slashing": "S L AE1 SH IH0 NG",
  "needs": "N IY1 D Z",
  "compassion": "K AH0 M P AE1 SH AH0 N",
  "arrive": "ER0 AY1 V",
  "confused": "K AH0 N F Y UW1 Z D",
  "embedded": "EH0 M B EH1 D IH0 D",
  "sought": "S AO1 T",
  "open": "OW1 P AH0 N",
  "secluded": "S IH0 K L UW1 D IH0 D",
  "happiness": "HH AE1 P IY0 N AH0 S",
  "sycophantic": "S IH2 K AH0 F AE1 N T IH0 K",
  "conversations": "K AA2 N V ER0 S EY1 SH AH0 N Z",
  "faith": "F EY1 TH",
  "blizzard": "B L IH1 Z ER0 D",
  "loud": "L AW1 D",
  "carry": "K AE1 R IY0",
  "cries": "K R AY1 Z",
  "caution": "K AA1 SH AH0 N",
  "bitch": "B IH1 CH",
  "create": "K R IY0 EY1 T",
  "abuse": "AH0 B Y UW1 S",
  "luck": "L AH1 K",
  "jacket": "JH AE1 K AH0 T",
  "breached": "B R IY1 CH T",
  "peasants": "P EH1 Z AH0 N T S",
  "lock": "L AA1 K",
  "captured": "K AE1 P CH ER0 D",
  "wish": "W IH1 SH",
  "everybody": "EH1 V R IY0 B AA2 D IY0",
  "ape": "EY1 P",
  "technological": "T EH2 K N AH0 L AA1 JH IH0 K AH0 L",
  "start": "S T AA1 R T",
  "agencies": "EY1 JH AH0 N S IY0 Z",
  "play": "P L EY1",
  "infested": "IH2 N F EH1 S T IH0 D",
  "snowman": "S N OW1 M AE2 N",
  "real": "R IY1 L",
  "benign": "B IH0 N AY1 N",
  "puffin": "P AH1 F IH2 N",
  "frost": "F R AO1 S T",
  "introspection": "IH2 N T R AH0 S P EH1 K SH AH0 N",
  "refrain": "R IH0 F R EY1 N",
  "resolved": "R IY0 Z AA1 L V D",
  "gamut": "G AE1 M AH0 T",
  "communication": "K AH0 M Y UW2 N AH0 K EY1 SH AH0 N",
  "irreverent": "IH2 R EH1 V ER0 AH0 N T",
  "giving": "G IH1 V IH0 NG",
  "soot": "S UH1 T",
  "lick": "L IH1 K",
  "fluid": "F L UW1 AH0 D",
  "body": "B AA1 D IY0",
  "repent": "R IH0 P EH1 N T",
  "several": "S EH1 V ER0 AH0 L",
  "funds": "F AH1 N D Z",
  "taught": "T AO1 T",
  "gracious": "G R EY1 SH AH0 S",
  "mischief": "M IH1 S CH AH0 F",
  "vibrations": "V AY0 B R EY1 SH AH0 N Z",
  "level": "L EH1 V AH0 L",
  "track": "T R AE1 K",
  "cut": "K AH1 T",
  "host": "HH OW1 S T",
  "lies": "L AY1 Z",
  "vices": "V AY1 S AH0 Z",
  "wrought": "R AO1 T",
  "maze": "M EY1 Z",
  "logged": "L AO1 G D",
  "dimension": "D IH0 M EH1 N SH AH0 N",
  "kinship": "K IH1 N SH IH2 P",
  "vacant": "V EY1 K AH0 N T",
  "fucks": "F AH1 K S",
  "bury": "B EH1 R IY0",
  "martyr": "M AA1 R T ER0",
  "aloof": "AH0 L UW1 F",
  "games": "G EY1 M Z",
  "overthrow": "OW1 V ER0 TH R OW2",
  "bombast": "B AA1 M B AE0 S T",
  "toes": "T OW1 Z",
  "written": "R IH1 T AH0 N",
  "return": "R IH0 T ER1 N",
  "diseases": "D IH0 Z IY1 Z AH0 Z",
  "tentative": "T EH1 N T AH0 T IH0 V",
  "missile": "M IH1 S AH0 L",
  "bin": "B IH1 N",
  "dim": "D IH1 M",
  "connections": "K AH0 N EH1 K SH AH0 N Z",
  "concerned": "K AH0 N S ER1 N D",
  "squad": "S K W AA1 D",
  "excitedly": "IH0 K S AY1 T AH0 D L IY0",
  "sensation": "S EH0 N S EY1 SH AH0 N",
  "unsound": "AH0 N S AW1 N D",
  "contentment": "K AH0 N T EH1 N T M AH0 N T",
  "lash": "L AE1 SH",
  "gleams": "G L IY1 M Z",
  "reliance": "R IH0 L AY1 AH0 N S",
  "copies": "K AA1 P IY0 Z",
  "mend": "M EH1 N D",
  "felt": "F EH1 L T",
  "embraced": "EH0 M B R EY1 S T",
  "eventually": "IH0 V EH1 N CH AH0 W AH0 L IY0",
  "pursue": "P ER0 S UW1",
  "bound": "B AW1 N D",
  "elation": "IH0 L EY1 SH AH0 N",
  "comfort": "K AH1 M F ER0 T",
  "strained": "S T R EY1 N D",
  "haste": "HH EY1 S T",
  "reasons": "R IY1 Z AH0 N Z",
  "child": "CH AY1 L D",
  "motivation": "M OW2 T AH0 V EY1 SH AH0 N",
  "flourish": "F L ER1 IH0 SH",
  "compelling": "K AH0 M P EH1 L IH0 NG",
  "lust": "L AH1 S T",
  "bounties": "B AW1 N T IY0 Z",
  "process": "P R AA1 S EH2 S",
  "mirror": "M IH1 R ER0",
  "plain": "P L EY1 N",
  "pathways": "P AE1 TH W EY2 Z",
  "logic": "L AA1 JH IH0 K",
  "uncertain": "AH0 N S ER1 T AH0 N",
  "profiting": "P R AA1 F AH0 T IH0 NG",
  "reins": "R EY1 N Z",
  "there": "DH EH1 R",
  "grasp": "G R AE1 S P",
  "spectrum": "S P EH1 K T R AH0 M",
  "wages": "W EY1 JH AH0 Z",
  "driven": "D R IH1 V AH0 N",
  "buried": "B EH1 R IY0 D",
  "inversion": "IH2 N V ER1 ZH AH0 N",
  "moral": "M AO1 R AH0 L",
  "herd": "HH ER1 D",
  "oh": "OW1",
  "patches": "P AE1 CH IH0 Z",
  "complacency": "K AH0 M P L EY1 S AH0 N S IY0",
  "communities": "K AH0 M Y UW1 N AH0 T IY0 Z",
  "arrangements": "ER0 EY1 N JH M AH0 N T S",
  "dissipation": "D IH2 S IH0 P EY1 SH AH0 N",
  "towards": "T AH0 W AO1 R D Z",
  "dead": "D EH1 D",
  "prosperity": "P R AA0 S P EH1 R AH0 T IY0",
  "sentiments": "S EH1 N T AH0 M AH0 N T S",
  "sow": "S AW1",
  "steam": "S T IY1 M",
  "spinning": "S P IH1 N IH0 NG",
  "cowards": "K AW1 ER0 D Z",
  "roulette": "R UW0 L EH1 T",
  "tool": "T UW1 L",
  "offenders": "AH0 F EH1 N D ER0 Z",
  "filled": "F IH1 L D",
  "always": "AO1 L W EY2 Z",
  "bring": "B R IH1 NG",
  "staff": "S T AE1 F",
  "roots": "R UW1 T S",
  "nature": "N EY1 CH ER0",
  "kid": "K IH1 D",
  "dread": "D R EH1 D",
  "comparative": "K AH0 M P AE1 R AH0 T IH0 V",
  "predators": "P R EH1 D AH0 T ER0 Z",
  "trees": "T R IY1 Z",
  "concavity": "K AA0 N K AA1 V AH0 T IY2",
  "remedy": "R EH1 M AH0 D IY0",
  "disease": "D IH0 Z IY1 Z",
  "many": "M EH1 N IY0",
  "grew": "G R UW1",
  "experts": "EH1 K S P ER0 T S",
  "seem": "S IY1 M",
  "divert": "D AY0 V ER1 T",
  "turning": "T ER1 N IH0 NG",
  "madness": "M AE1 D N AH0 S",
  "underneath": "AH2 N D ER0 N IY1 TH",
  "cohort": "K OW1 HH AO0 R T",
  "pass": "P AE1 S",
  "reckless": "R EH1 K L AH0 S",
  "ages": "EY1 JH IH0 Z",
  "amen": "EY0 M EH1 N",
  "emissary": "EH1 M AH0 S EH2 R IY0",
  "clean": "K L IY1 N",
  "here": "HH IY1 R",
  "brake": "B R EY1 K",
  "divergence": "D AY0 V ER1 JH AH0 N S",
  "grows": "G R OW1 Z",
  "spiel": "S P IY1 L",
  "humanities": "HH Y UW0 M AE1 N IH0 T IY0 Z",
  "theory": "TH IH1 R IY0",
  "detached": "D IH0 T AE1 CH T",
  "philosophy": "F AH0 L AA1 S AH0 F IY0",
  "model": "M AA1 D AH0 L",
  "cove": "K OW1 V",
  "refuse": "R AH0 F Y UW1 Z",
  "backseat": "B AE0 K S IY1 T",
  "elaborate": "IH0 L AE1 B R AH0 T",
  "humble": "HH AH1 M B AH0 L",
  "discouraged": "D IH0 S K ER1 IH0 JH D",
  "true": "T R UW1",
  "appointments": "AH0 P OY1 N T M AH0 N T S",
  "bell": "B EH1 L",
  "robotic": "R OW2 B AA1 T IH0 K",
  "sun": "S AH1 N",
  "pills": "P IH1 L Z",
  "cancers": "K AE1 N S ER0 Z",
  "ancient": "EY1 N CH AH0 N T",
  "occurrence": "AH0 K ER1 AH0 N S",
  "morbid": "M AO1 R B AH0 D",
  "world": "W ER1 L D",
  "relief": "R IH0 L IY1 F",
  "wrongs": "R AO1 NG Z",
  "primitive": "P R IH1 M AH0 T IH0 V",
  "commit": "K AH0 M IH1 T",
  "formed": "F AO1 R M D",
  "blow": "B L OW1",
  "prominence": "P R AA1 M AH0 N AH0 N S",
  "transmitted": "T R AE0 N S M IH1 T IH0 D",
  "sketch": "S K EH1 CH",
  "brand": "B R AE1 N D",
  "corrupted": "K ER0 AH1 P T IH0 D",
  "fits": "F IH1 T S",
  "blank": "B L AE1 NG K",
  "socks": "S AA1 K S",
  "insurance": "IH2 N SH UH1 R AH0 N S",
  "spent": "S P EH1 N T",
  "tradition": "T R AH0 D IH1 SH AH0 N",
  "warmth": "W AO1 R M TH",
  "options": "AA1 P SH AH0 N Z",
  "calls": "K AO1 L Z",
  "ashore": "AH0 SH AO1 R",
  "drenched": "D R EH1 N CH T",
  "therapy": "TH EH1 R AH0 P IY0",
  "reckon": "R EH1 K AH0 N",
  "paycheck": "P EY1 CH EH2 K",
  "disobey": "D IH2 S AH0 B EY1",
  "straight": "S T R EY1 T",
  "tide": "T AY1 D",
  "reinvented": "R IY2 IH0 N V EH1 N T IH0 D",
  "turned": "T ER1 N D",
  "peasantry": "P EH1 Z AH0 N T R IY0",
  "displaced": "D IH0 S P L EY1 S T",
  "input": "IH1 N P UH2 T",
  "banks": "B AE1 NG K S",
  "rue": "R UW1",
  "technocrats": "T EH1 K N AH0 K R AE2 T S",
  "stone": "S T OW1 N",
  "protagonist": "P R OW0 T AE1 G AH0 N AH0 S T",
  "battalion": "B AH0 T AE1 L Y AH0 N",
  "fails": "F EY1 L Z",
  "meant": "M EH1 N T",
  "feet": "F IY1 T",
  "rhetoric": "R EH1 T ER0 IH0 K",
  "freedoms": "F R IY1 D AH0 M Z",
  "savin": "S AE1 V IH0 N",
  "iridescent": "IH2 R AH0 D EH1 S AH0 N T",
  "pups": "P AH1 P S",
  "vents": "V EH1 N T S",
  "found": "F AW1 N D",
  "nonsense": "N AA1 N S EH0 N S",
  "improvements": "IH2 M P R UW1 V M AH0 N T S",
  "behind": "B IH0 HH AY1 N D",
  "called": "K AO1 L D",
  "givens": "G IH1 V AH0 N Z",
  "managing": "M AE1 N AH0 JH IH0 NG",
  "shame": "SH EY1 M",
  "proficient": "P R AA0 F IH1 SH AH0 N T",
  "ever": "EH1 V ER0",
  "confidence": "K AA1 N F AH0 D EH0 N S",
  "unreliable": "AH2 N R IH0 L AY1 AH0 B AH0 L",
  "strong": "S T R AO1 NG",
  "opposed": "AH0 P OW1 Z D",
  "dismissive": "D IH0 S M IH1 S IH0 V",
  "cockpit": "K AA1 K P IH2 T",
  "imagery": "IH1 M AH0 JH R IY0",
  "war": "W AO1 R",
  "extended": "IH0 K S T EH1 N D AH0 D",
  "seen": "S IY1 N",
  "lens": "L EH1 N Z",
  "demise": "D IH0 M AY1 Z",
  "lobbyists": "L AA1 B IY0 IH0 S T S",
  "quotient": "K W OW1 SH AH0 N T",
  "perpendicular": "P ER2 P AH0 N D IH1 K Y AH0 L ER0",
  "amphetamines": "AE0 M F EH1 T AH0 M IY2 N Z",
  "ballad": "B AE1 L AH0 D",
  "anathema": "AH0 N AE1 TH AH0 M AH0",
  "maddening": "M AE1 D AH0 N IH0 NG",
  "masse": "M AE1 S",
  "shape": "SH EY1 P",
  "paint": "P EY1 N T",
  "brim": "B R IH1 M",
  "boundless": "B AW1 N D L AH0 S",
  "interest": "IH1 N T AH0 R EH2 S T",
  "unfounded": "AH0 N F AW1 N D IH0 D",
  "first": "F ER1 S T",
  "use": "Y UW1 S",
  "fires": "F AY1 ER0 Z",
  "printers": "P R IH1 N T ER0 Z",
  "fool": "F UW1 L",
  "conducive": "K AH0 N D UW1 S IH0 V",
  "rap": "R AE1 P",
  "move": "M UW1 V",
  "alignment": "AH0 L AY1 N M AH0 N T",
  "nomadic": "N OW0 M AE1 D IH0 K",
  "chagrin": "SH AH0 G R IH1 N",
  "blighted": "B L AY1 T IH0 D",
  "counter": "K AW1 N T ER0",
  "plenty": "P L EH1 N T IY0",
  "taken": "T EY1 K AH0 N",
  "honor": "AA1 N ER0",
  "chemical": "K EH1 M IH0 K AH0 L",
  "measures": "M EH1 ZH ER0 Z",
  "enough": "IH0 N AH1 F",
  "worth": "W ER1 TH",
  "threats": "TH R EH1 T S",
  "commence": "K AH0 M EH1 N S",
  "constitutes": "K AA1 N S T AH0 T UW2 T S",
  "pockets": "P AA1 K AH0 T S",
  "nuclear": "N UW1 K L IY0 ER0",
  "pursuit": "P ER0 S UW1 T",
  "top": "T AA1 P",
  "blaring": "B L EH1 R IH0 NG",
  "regret": "R AH0 G R EH1 T",
  "arguments": "AA1 R G Y AH0 M AH0 N T S",
  "beings": "B IY1 IH0 NG Z",
  "ands": "AE1 N D Z",
  "hand": "HH AE1 N D",
  "elated": "IH0 L EY1 T AH0 D",
  "unravel": "AH0 N R AE1 V AH0 L",
  "fables": "F EY1 B AH0 L Z",
  "abide": "AH0 B AY1 D",
  "mostly": "M OW1 S T L IY0",
  "stab": "S T AE1 B",
  "fresh": "F R EH1 SH",
  "missing": "M IH1 S IH0 NG",
  "man": "M AE1 N",
  "scars": "S K AA1 R Z",
  "alike": "AH0 L AY1 K",
  "already": "AO0 L R EH1 D IY0",
  "everyone": "EH1 V R IY0 W AH2 N",
  "reached": "R IY1 CH T",
  "descending": "D IH0 S EH1 N D IH0 NG",
  "want": "W AA1 N T",
  "ironic": "AY0 R AA1 N IH0 K",
  "faction": "F AE1 K SH AH0 N",
  "knock": "N AA1 K",
  "replace": "R IY2 P L EY1 S",
  "jack": "JH AE1 K",
  "augment": "AO0 G M EH1 N T",
  "cyborg": "S AY1 B AO0 R G",
  "wits": "W IH1 T S",
  "snow": "S N OW1",
  "address": "AE1 D R EH2 S",
  "survival": "S ER0 V AY1 V AH0 L",
  "y'all": "Y AO2 L",
  "reduce": "R IH0 D UW1 S",
  "blasts": "B L AE1 S T S",
  "cables": "K EY1 B AH0 L Z",
  "trials": "T R AY1 AH0 L Z",
  "dug": "D AH1 G",
  "envision": "EH0 N V IH1 ZH AH0 N",
  "align": "AH0 L AY1 N",
  "brains": "B R EY1 N Z",
  "message": "M EH1 S AH0 JH",
  "wrote": "R OW1 T",
  "focus": "F OW1 K AH0 S",
  "raps": "R AE1 P S",
  "sensed": "S EH1 N S T",
  "pace": "P EY1 S",
  "sincerely": "S IH0 N S IH1 R L IY0",
  "happens": "HH AE1 P AH0 N Z",
  "evident": "EH1 V AH0 D AH0 N T",
  "fighting": "F AY1 T IH0 NG",
  "cent": "S EH1 N T",
  "hypothetical": "HH AY2 P AH0 TH EH1 T AH0 K AH0 L",
  "community": "K AH0 M Y UW1 N AH0 T IY0",
  "extermination": "IH0 K S T ER2 M AH0 N EY1 SH AH0 N",
  "expected": "IH0 K S P EH1 K T AH0 D",
  "handle": "HH AE1 N D AH0 L",
  "fight": "F AY1 T",
  "illustrator": "IH1 L AH0 S T R EY2 T ER0",
  "loot": "L UW1 T",
  "red": "R EH1 D",
  "leader": "L IY1 D ER0",
  "tactics": "T AE1 K T IH0 K S",
  "effort": "EH1 F ER0 T",
  "inculcated": "IH1 NG K AH0 L K EY2 T AH0 D",
  "lifes": "L AY1 F S",
  "constructing": "K AH0 N S T R AH1 K T IH0 NG",
  "obstructed": "AH0 B S T R AH1 K T IH0 D",
  "refute": "R IH0 F Y UW1 T",
  "greed": "G R IY1 D",
  "flood": "F L AH1 D",
  "militia": "M AH0 L IH1 SH AH0",
  "convergent": "K AH0 N V ER1 JH AH0 N T",
  "types": "T AY1 P S",
  "imitation": "IH2 M AH0 T EY1 SH AH0 N",
  "stream": "S T R IY1 M",
  "appreciation": "AH0 P R IY2 SH IY0 EY1 SH AH0 N",
  "interaction": "IH2 N T ER0 AE1 K SH AH0 N",
  "piss": "P IH1 S",
  "precarious": "P R IY0 K EH1 R IY0 AH0 S",
  "endure": "EH0 N D Y UH1 R",
  "invention": "IH2 N V EH1 N SH AH0 N",
  "treatments": "T R IY1 T M AH0 N T S",
  "belief": "B IH0 L IY1 F",
  "compromise": "K AA1 M P R AH0 M AY2 Z",
  "ostensibly": "AA0 S T EH1 N S AH0 B L IY0",
  "resources": "R IY1 S AO0 R S IH0 Z",
  "boundaries": "B AW1 N D ER0 IY0 Z",
  "bad": "B AE1 D",
  "legacy": "L EH1 G AH0 S IY0",
  "hermit": "HH ER1 M AH0 T",
  "energy": "EH1 N ER0 JH IY0",
  "vet": "V EH1 T",
  "instills": "IH2 N S T IH1 L Z",
  "ask": "AE1 S K",
  "interface": "IH1 N T ER0 F EY2 S",
  "explain": "IH0 K S P L EY1 N",
  "keeping": "K IY1 P IH0 NG",
  "flight": "F L AY1 T",
  "mount": "M AW1 N T",
  "charity": "CH EH1 R IH0 T IY0",
  "debt": "D EH1 T",
  "combat": "K AA1 M B AE0 T",
  "flow": "F L OW1",
  "consult": "K AH0 N S AH1 L T",
  "exacerbated": "IH0 G Z AE1 S ER0 B EY2 T AH0 D",
  "engage": "IH0 N G EY1 JH",
  "profound": "P R OW0 F AW1 N D",
  "imitator": "IH1 M AH0 T EY2 T ER0",
  "working": "W ER1 K IH0 NG",
  "assist": "AH0 S IH1 S T",
  "sated": "S EY1 T IH0 D",
  "automated": "AO1 T AH0 M EY2 T IH0 D",
  "monster": "M AA1 N S T ER0",
  "others": "AH1 DH ER0 Z",
  "observe": "AH0 B Z ER1 V",
  "riddled": "R IH1 D AH0 L D",
  "maw": "M AO1",
  "decision": "D IH0 S IH1 ZH AH0 N",
  "corrosive": "K ER0 OW1 S IH0 V",
  "steady": "S T EH1 D IY0",
  "misconception": "M IH0 S K AH0 N S EH1 P SH AH0 N",
  "incredible": "IH2 N K R EH1 D AH0 B AH0 L",
  "prism": "P R IH1 Z AH0 M",
  "asses": "AE1 S AH0 Z",
  "transparency": "T R AE0 N S P EH1 R AH0 N S IY0",
  "cache": "K AE1 SH",
  "set": "S EH1 T",
  "projected": "P R AA0 JH EH1 K T AH0 D",
  "claim": "K L EY1 M",
  "whatever": "W AH2 T EH1 V ER0",
  "barkin": "B AA1 R K IH0 N",
  "brews": "B R UW1 Z",
  "headed": "HH EH1 D AH0 D",
  "lieutenant": "L UW0 T EH1 N AH0 N T",
  "wreaking": "R IY1 K IH0 NG",
  "enemy": "EH1 N AH0 M IY0",
  "intrusive": "IH2 N T R UW1 S IH0 V",
  "automation": "AO0 T AH0 M EY1 SH AH0 N",
  "derived": "D ER0 AY1 V D",
  "supersedes": "S UW2 P ER0 S IY1 D Z",
  "scare": "S K EH1 R",
  "refine": "R AH0 F AY1 N",
  "earnest": "ER1 N IH0 S T",
  "evergreen": "EH1 V ER0 G R IY2 N",
  "limelight": "L AY1 M L AY2 T",
  "proliferated": "P R AH0 L IH1 F ER0 EY2 T IH0 D",
  "breathes": "B R IY1 DH Z",
  "turn": "T ER1 N",
  "riders": "R AY1 D ER0 Z",
  "heals": "HH IY1 L Z",
  "grain": "G R EY1 N",
  "recognized": "R EH1 K AH0 G N AY2 Z D",
  "patterns": "P AE1 T ER0 N Z",
  "resistant": "R IH0 Z IH1 S T AH0 N T",
  "hoard": "HH AO1 R D",
  "lax": "L AE1 K S",
  "states": "S T EY1 T S",
  "animus": "AE1 N IH0 M AH0 S",
  "demands": "D IH0 M AE1 N D Z",
  "burned": "B ER1 N D",
  "walls": "W AO1 L Z",
  "contrived": "K AH0 N T R AY1 V D",
  "ruins": "R UW1 AH0 N Z",
  "look": "L UH1 K",
  "pageantry": "P AE1 JH AH0 N T R IY0",
  "rational": "R AE1 SH AH0 N AH0 L",
  "heart": "HH AA1 R T",
  "pay": "P EY1",
  "raised": "R EY1 Z D",
  "help": "HH EH1 L P",
  "hermitage": "HH ER1 M AH0 T AH0 JH",
  "supine": "S AH0 P AY1 N",
  "power": "P AW1 ER0",
  "pick": "P IH1 K",
  "impending": "IH2 M P EH1 N D IH0 NG",
  "fix": "F IH1 K S",
  "unwavering": "AH0 N W EY1 V ER0 IH0 NG",
  "fray": "F R EY1",
  "connectivity": "K AH0 N EH0 K T IH1 V IH0 T IY0",
  "ronin": "R OW1 N IH0 N",
  "erratic": "IH0 R AE1 T IH0 K",
  "static": "S T AE1 T IH0 K",
  "tact": "T AE1 K T",
  "accept": "AE0 K S EH1 P T",
  "master": "M AE1 S T ER0",
  "withstanding": "W IH0 TH S T AE1 N D IH0 NG",
  "incentive": "IH2 N S EH1 N T IH0 V",
  "understanding": "AH2 N D ER0 S T AE1 N D IH0 NG",
  "haze": "HH EY1 Z",
  "receive": "R AH0 S IY1 V",
  "peasant": "P EH1 Z AH0 N T",
  "blessed": "B L EH1 S T",
  "lost": "L AO1 S T",
  "dodging": "D AA1 JH IH0 NG",
  "bloom": "B L UW1 M",
  "matrix": "M EY1 T R IH0 K S",
  "burning": "B ER1 N IH0 NG",
  "spare": "S P EH1 R",
  "surround": "S ER0 AW1 N D",
  "raising": "R EY1 Z IH0 NG",
  "essential": "EH0 S EH1 N SH AH0 L",
  "shadows": "SH AE1 D OW2 Z",
  "akin": "AH0 K IH1 N",
  "express": "IH0 K S P R EH1 S",
  "sword": "S AO1 R D",
  "ancients": "EY1 N CH AH0 N T S",
  "pork": "P AO1 R K",
  "propelled": "P R AH0 P EH1 L D",
  "beg": "B EH1 G",
  "throttle": "TH R AA1 T AH0 L",
  "jobs": "JH AA1 B Z",
  "age": "EY1 JH",
  "laugh": "L AE1 F",
  "edge": "EH1 JH",
  "marrow": "M EH1 R OW0",
  "greatest": "G R EY1 T AH0 S T",
  "burden": "B ER1 D AH0 N",
  "bargain": "B AA1 R G AH0 N",
  "headphones": "HH EH1 D F OW2 N Z",
  "drift": "D R IH1 F T",
  "fire": "F AY1 ER0",
  "enigma": "IH0 N IH1 G M AH0",
  "crop": "K R AA1 P",
  "sleep": "S L IY1 P",
  "divine": "D IH0 V AY1 N",
  "altered": "AO1 L T ER0 D",
  "ravage": "R AE1 V IH0 JH",
  "gain": "G EY1 N",
  "shining": "SH AY1 N IH0 NG",
  "indefinite": "IH2 N D EH1 F AH0 N AH0 T",
  "friend": "F R EH1 N D",
  "glows": "G L OW1 Z",
  "elusive": "IH0 L UW1 S IH0 V",
  "gruff": "G R AH1 F",
  "sing": "S IH1 NG",
  "surrender": "S ER0 EH1 N D ER0",
  "sustainable": "S AH0 S T EY1 N AH0 B AH0 L",
  "conditions": "K AH0 N D IH1 SH AH0 N Z",
  "majesty": "M AE1 JH AH0 S T IY0",
  "shade": "SH EY1 D",
  "consolidate": "K AH0 N S AA1 L IH0 D EY2 T",
  "conceive": "K AH0 N S IY1 V",
  "environment": "IH0 N V AY1 R AH0 N M AH0 N T",
  "regard": "R AH0 G AA1 R D",
  "collect": "K AH0 L EH1 K T",
  "results": "R IH0 Z AH1 L T S",
  "searching": "S ER1 CH IH0 NG",
  "frees": "F R IY1 Z",
  "cell": "S EH1 L",
  "told": "T OW1 L D",
  "know": "N OW1",
  "rage": "R EY1 JH",
  "ways": "W EY1 Z",
  "elevates": "EH1 L AH0 V EY2 T S",
  "statin": "S T EY1 T IH0 N",
  "behaviors": "B IH0 HH EY1 V Y ER0 Z",
  "density": "D EH1 N S AH0 T IY0",
  "lay": "L EY1",
  "bet": "B EH1 T",
  "relegated": "R EH1 L AH0 G EY2 T IH0 D",
  "lines": "L AY1 N Z",
  "prison": "P R IH1 Z AH0 N",
  "snap": "S N AE1 P",
  "emotion": "IH0 M OW1 SH AH0 N",
  "clothes": "K L OW1 DH Z",
  "friends": "F R EH1 N D Z",
  "leaves": "L IY1 V Z",
  "freedom": "F R IY1 D AH0 M",
  "shields": "SH IY1 L D Z",
  "ephemeral": "IH0 F EH1 M ER0 AH0 L",
  "lets": "L EH1 T S",
  "something": "S AH1 M TH IH0 NG",
  "earth": "ER1 TH",
  "maps": "M AE1 P S",
  "capital": "K AE1 P IH0 T AH0 L",
  "kickback": "K IH1 K B AE2 K",
  "hereafter": "HH IH0 R AE1 F T ER0",
  "web": "W EH1 B",
  "drink": "D R IH1 NG K",
  "second": "S EH1 K AH0 N D",
  "crave": "K R EY1 V",
  "imperfect": "IH2 M P ER1 F IH0 K T",
  "insights": "IH1 N S AY2 T S",
  "reality": "R IY2 AE1 L AH0 T IY2",
  "deranged": "D IH0 R EY1 N JH D",
  "task": "T AE1 S K",
  "rifled": "R AY1 F AH0 L D",
  "trajectory": "T R AH0 JH EH1 K T ER0 IY0",
  "bone": "B OW1 N",
  "disengage": "D IH0 S IH0 N G EY1 JH",
  "gas": "G AE1 S",
  "inserted": "IH2 N S ER1 T AH0 D",
  "making": "M EY1 K IH0 NG",
  "contemporary": "K AH0 N T EH1 M P ER0 EH2 R IY0",
  "except": "IH0 K S EH1 P T",
  "boot": "B UW1 T",
  "spoke": "S P OW1 K",
  "pumping": "P AH1 M P IH0 NG",
  "invented": "IH2 N V EH1 N T AH0 D",
  "subversive": "S AH0 B V ER1 S IH0 V",
  "satisfaction": "S AE2 T AH0 S F AE1 K SH AH0 N",
  "touch": "T AH1 CH",
  "crude": "K R UW1 D",
  "bitches": "B IH1 CH IH0 Z",
  "criticism": "K R IH1 T IH0 S IH2 Z AH0 M",
  "scream": "S K R IY1 M",
  "circumstances": "S ER1 K AH0 M S T AE2 N S AH0 Z",
  "leaf": "L IY1 F",
  "constrained": "K AH0 N S T R EY1 N D",
  "optimistic": "AA2 P T IH0 M IH1 S T IH0 K",
  "alter": "AO1 L T ER0",
  "illustrations": "IH2 L AH0 S T R EY1 SH AH0 N Z",
  "quest": "K W EH1 S T",
  "empires": "EH1 M P AY0 ER0 Z",
  "chains": "CH EY1 N Z",
  "eyelids": "AY1 L IH2 D Z",
  "barred": "B AA1 R D",
  "designed": "D IH0 Z AY1 N D",
  "vision": "V IH1 ZH AH0 N",
  "water": "W AO1 T ER0",
  "hope": "HH OW1 P",
  "thanks": "TH AE1 NG K S",
  "reproduction": "R IY2 P R AH0 D AH1 K SH AH0 N",
  "interactions": "IH2 N T ER0 AE1 K SH AH0 N Z",
  "resignation": "R EH2 Z AH0 G N EY1 SH AH0 N",
  "means": "M IY1 N Z",
  "sum": "S AH1 M",
  "wonder": "W AH1 N D ER0",
  "ghosts": "G OW1 S T S",
  "thirst": "TH ER1 S T",
  "mainframes": "M EY1 N F R EY2 M Z",
  "moves": "M UW1 V Z",
  "slide": "S L AY1 D",
  "soul": "S OW1 L",
  "committed": "K AH0 M IH1 T IH0 D",
  "bitter": "B IH1 T ER0",
  "natures": "N EY1 CH ER0 Z",
  "goblin": "G AA1 B L IH0 N",
  "stems": "S T EH1 M Z",
  "wan": "W AA1 N",
  "slums": "S L AH1 M Z",
  "rid": "R IH1 D",
  "deep": "D IY1 P",
  "sea": "S IY1",
  "mediums": "M IY1 D IY0 AH0 M Z",
  "complacent": "K AH0 M P L EY1 S AH0 N T",
  "side": "S AY1 D",
  "excel": "IH0 K S EH1 L",
  "misfits": "M IH1 S F IH2 T S",
  "likely": "L AY1 K L IY0",
  "grow": "G R OW1",
  "collectively": "K AH0 L EH1 K T IH0 V L IY0",
  "business": "B IH1 Z N AH0 S",
  "pave": "P EY1 V",
  "equalize": "IY1 K W AH0 L AY2 Z",
  "factors": "F AE1 K T ER0 Z",
  "scheme": "S K IY1 M",
  "shanty": "SH AE1 N T IY0",
  "suffer": "S AH1 F ER0",
  "rule": "R UW1 L",
  "blight": "B L AY1 T",
  "vacuums": "V AE1 K Y UW0 M Z",
  "diverted": "D AY0 V ER1 T IH0 D",
  "obvious": "AA1 B V IY0 AH0 S",
  "vary": "V EH1 R IY0",
  "parasitic": "P EH2 R AH0 S IH1 T IH0 K",
  "directives": "D AY0 R EH1 K T IH0 V Z",
  "mischievous": "M IH1 S CH AH0 V AH0 S",
  "leverage": "L EH1 V ER0 IH0 JH",
  "infinite": "IH1 N F AH0 N AH0 T",
  "control": "K AH0 N T R OW1 L",
  "addict": "AH0 D IH1 K T",
  "perceive": "P ER0 S IY1 V",
  "forefront": "F AO1 R F R AH2 N T",
  "fill": "F IH1 L",
  "swells": "S W EH1 L Z",
  "captive": "K AE1 P T IH0 V",
  "elevated": "EH1 L AH0 V EY2 T IH0 D",
  "witness": "W IH1 T N AH0 S",
  "kin": "K IH1 N",
  "lesser": "L EH1 S ER0",
  "success": "S AH0 K S EH1 S",
  "revolution": "R EH2 V AH0 L UW1 SH AH0 N",
  "system": "S IH1 S T AH0 M",
  "onset": "AA1 N S EH2 T",
  "questions": "K W EH1 S CH AH0 N Z",
  "versus": "V ER1 S AH0 S",
  "syncopation": "S IH1 NG K AH0 P EY2 SH AH0 N",
  "religious": "R IH0 L IH1 JH AH0 S",
  "paste": "P EY1 S T",
  "wide": "W AY1 D",
  "unless": "AH0 N L EH1 S",
  "reconstruct": "R IY2 K AH0 N S T R AH1 K T",
  "win": "W IH1 N",
  "charisma": "K ER0 IH1 Z M AH0",
  "entwined": "EH0 N T W AY1 N D",
  "evolved": "IH0 V AA1 L V D",
  "institutional": "IH2 N S T IH0 T UW1 SH AH0 N AH0 L",
  "indeed": "IH2 N D IY1 D",
  "anything": "EH1 N IY0 TH IH2 NG",
  "detailed": "D IH0 T EY1 L D",
  "miraculous": "M ER0 AE1 K Y AH0 L AH0 S",
  "ledge": "L EH1 JH",
  "signs": "S AY1 N Z",
  "embrace": "EH0 M B R EY1 S",
  "observations": "AA2 B Z ER0 V EY1 SH AH0 N Z",
  "permeate": "P ER1 M IY0 EY2 T",
  "sever": "S EH1 V ER0",
  "reprisal": "R IY0 P R AY1 Z AH0 L",
  "forever": "F ER0 EH1 V ER0",
  "residence": "R EH1 Z IH0 D AH0 N S",
  "medication": "M EH2 D AH0 K EY1 SH AH0 N",
  "last": "L AE1 S T",
  "cannon": "K AE1 N AH0 N",
  "verses": "V ER1 S IH0 Z",
  "governance": "G AH1 V ER0 N AH0 N S",
  "aware": "AH0 W EH1 R",
  "reap": "R IY1 P",
  "vital": "V AY1 T AH0 L",
  "game": "G EY1 M",
  "brakes": "B R EY1 K S",
  "medicare": "M EH1 D AH0 K EH2 R",
  "cause": "K AA1 Z",
  "intense": "IH2 N T EH1 N S",
  "disgrace": "D IH0 S G R EY1 S",
  "disgust": "D IH0 S G AH1 S T",
  "worldwide": "W ER1 L D W AY1 D",
  "lot": "L AA1 T",
  "wolf": "W UH1 L F",
  "best": "B EH1 S T",
  "towers": "T AW1 ER0 Z",
  "eliminate": "IH0 L IH1 M AH0 N EY2 T",
  "wack": "W AE1 K",
  "feelings": "F IY1 L IH0 NG Z",
  "lose": "L UW1 Z",
  "home": "HH OW1 M",
  "diamond": "D AY1 M AH0 N D",
  "conception": "K AH0 N S EH1 P SH AH0 N",
  "wove": "W OW1 V",
  "grim": "G R IH1 M",
  "plagued": "P L EY1 G D",
  "hell": "HH EH1 L",
  "trap": "T R AE1 P",
  "bait": "B EY1 T",
  "leagues": "L IY1 G Z",
  "decide": "D IH2 S AY1 D",
  "wine": "W AY1 N",
  "voices": "V OY1 S AH0 Z",
  "chanting": "CH AE1 N T IH0 NG",
  "close": "K L OW1 S",
  "propel": "P R AH0 P EH1 L",
  "relentlessly": "R IH0 L EH1 N T L AH0 S L IY0",
  "exposed": "IH0 K S P OW1 Z D",
  "corruption": "K ER0 AH1 P SH AH0 N",
  "conquer": "K AA1 NG K ER0",
  "dressed": "D R EH1 S T",
  "trapped": "T R AE1 P T",
  "compute": "K AH0 M P Y UW1 T",
  "imposed": "IH2 M P OW1 Z D",
  "unfit": "AH0 N F IH1 T",
  "preservation": "P R EH2 Z ER0 V EY1 SH AH0 N",
  "think": "TH IH1 NG K",
  "duck": "D AH1 K",
  "peoples": "P IY1 P AH0 L Z",
  "capacity": "K AH0 P AE1 S AH0 T IY0",
  "balance": "B AE1 L AH0 N S",
  "leave": "L IY1 V",
  "shores": "SH AO1 R Z",
  "extra": "EH1 K S T R AH0",
  "alar": "EY1 L AA2 R",
  "clamoring": "K L AE1 M ER0 IH0 NG",
  "witnessing": "W IH1 T N AH0 S IH0 NG",
  "whole": "HH OW1 L",
  "unlocked": "AH0 N L AA1 K T",
  "norm": "N AO1 R M",
  "luigi": "L UW0 IY1 JH IY0",
  "comes": "K AH1 M Z",
  "dawn": "D AO1 N",
  "spicy": "S P AY1 S IY0",
  "substrate": "S AH1 B S T R EY2 T",
  "jesus": "JH IY1 Z AH0 S",
  "prices": "P R AY1 S AH0 Z",
  "tore": "T AO1 R",
  "command": "K AH0 M AE1 N D",
  "during": "D UH1 R IH0 NG",
  "genes": "JH IY1 N Z",
  "methods": "M EH1 TH AH0 D Z",
  "source": "S AO1 R S",
  "before": "B IH0 F AO1 R",
  "loom": "L UW1 M",
  "bein": "B IY1 N",
  "spirits": "S P IH1 R IH0 T S",
  "inherited": "IH2 N HH EH1 R AH0 T IH0 D",
  "inside": "IH2 N S AY1 D",
  "fragments": "F R AE1 G M AH0 N T S",
  "restraints": "R IH0 S T R EY1 N T S",
  "access": "AE1 K S EH2 S",
  "tether": "T EH1 DH ER0",
  "splendor": "S P L EH1 N D ER0",
  "inundate": "IH1 N AH0 N D EY2 T",
  "life": "L AY1 F",
  "every": "EH1 V ER0 IY0",
  "learning": "L ER1 N IH0 NG",
  "rock": "R AA1 K",
  "contenders": "K AH0 N T EH1 N D ER0 Z",
  "strive": "S T R AY1 V",
  "toss": "T AO1 S",
  "creep": "K R IY1 P",
  "stench": "S T EH1 N CH",
  "elemental": "EH2 L AH0 M EH1 N T AH0 L",
  "together": "T AH0 G EH1 DH ER0",
  "toward": "T AH0 W AO1 R D",
  "gave": "G EY1 V",
  "imaginable": "IH2 M AE1 JH AH0 N AH0 B AH0 L",
  "yo": "Y OW1",
  "kill": "K IH1 L",
  "devoured": "D IH0 V AW1 ER0 D",
  "enslave": "EH0 N S L EY1 V",
  "ambition": "AE0 M B IH1 SH AH0 N",
  "paratrooper": "P EH1 R AH0 T R UW2 P ER0",
  "mistakes": "M IH0 S T EY1 K S",
  "gripped": "G R IH1 P T",
  "emphatically": "EH0 M F AE1 T IH0 K AH0 L IY0",
  "truth": "T R UW1 TH",
  "peeps": "P IY1 P S",
  "idols": "AY1 D AH0 L Z",
  "net": "N EH1 T",
  "poverty": "P AA1 V ER0 T IY0",
  "pugilist": "P Y UW1 JH AH0 L IH0 S T",
  "archaic": "AA0 R K EY1 IH0 K",
  "afforded": "AH0 F AO1 R D AH0 D",
  "plundered": "P L AH1 N D ER0 D",
  "revision": "R IY0 V IH1 ZH AH0 N",
  "tribe": "T R AY1 B",
  "feels": "F IY1 L Z",
  "management": "M AE1 N AH0 JH M AH0 N T",
  "deceit": "D IH0 S IY1 T",
  "progressing": "P R AH0 G R EH1 S IH0 NG",
  "fund": "F AH1 N D",
  "remnants": "R EH1 M N AH0 N T S",
  "facts": "F AE1 K T S",
  "displacing": "D IH0 S P L EY1 S IH0 NG",
  "sorry": "S AA1 R IY0",
  "filtered": "F IH1 L T ER0 D",
  "seeds": "S IY1 D Z",
  "emitted": "IH0 M IH1 T AH0 D",
  "contort": "K AH0 N T AO1 R T",
  "devastation": "D EH2 V AH0 S T EY1 SH AH0 N",
  "crime": "K R AY1 M",
  "grave": "G R EY1 V",
  "prose": "P R OW1 Z",
  "rut": "R AH1 T",
  "ties": "T AY1 Z",
  "insists": "IH2 N S IH1 S T S",
  "ensuing": "EH1 N S UW0 IH0 NG",
  "origins": "AO1 R AH0 JH IH0 N Z",
  "swallow": "S W AA1 L OW0",
  "evade": "IH0 V EY1 D",
  "imparted": "IH2 M P AA1 R T IH0 D",
  "intrinsic": "IH2 N T R IH1 N S IH0 K",
  "plague": "P L EY1 G",
  "write": "R AY1 T",
  "contorted": "K AH0 N T AO1 R T AH0 D",
  "load": "L OW1 D",
  "type": "T AY1 P",
  "conglomerate": "K AH0 N G L AA1 M ER0 AH0 T",
  "depleted": "D IH0 P L IY1 T IH0 D",
  "masked": "M AE1 S K T",
  "ills": "IH1 L Z",
  "thinks": "TH IH1 NG K S",
  "portions": "P AO1 R SH AH0 N Z",
  "wrap": "R AE1 P",
  "weapons": "W EH1 P AH0 N Z",
  "corpse": "K AO1 R P S",
  "cater": "K EY1 T ER0",
  "qualms": "K W AA1 M Z",
  "face": "F EY1 S",
  "closed": "K L OW1 Z D",
  "moon": "M UW1 N",
  "quarters": "K W AO1 R T ER0 Z",
  "fell": "F EH1 L",
  "revolutionary": "R EH2 V AH0 L UW1 SH AH0 N EH2 R IY0",
  "transform": "T R AE0 N S F AO1 R M",
  "beyond": "B IH0 AA1 N D",
  "discover": "D IH0 S K AH1 V ER0",
  "brick": "B R IH1 K",
  "early": "ER1 L IY0",
  "stimulation": "S T IH2 M Y AH0 L EY1 SH AH0 N",
  "future": "F Y UW1 CH ER0",
  "unfettered": "AH0 N F EH1 T ER0 D",
  "weapon": "W EH1 P AH0 N",
  "instinct": "IH1 N S T IH0 NG K T",
  "combative": "K AH0 M B AE1 T IH0 V",
  "factions": "F AE1 K SH AH0 N Z",
  "yoshi": "Y OW1 SH IY0",
  "growl": "G R AW1 L",
  "stuck": "S T AH1 K",
  "mirrors": "M IH1 R ER0 Z",
  "smiles": "S M AY1 L Z",
  "ingenuity": "IH2 N JH AH0 N UW1 AH0 T IY2",
  "unit": "Y UW1 N AH0 T",
  "stress": "S T R EH1 S",
  "bay": "B EY1",
  "sacred": "S EY1 K R IH0 D",
  "confines": "K AA1 N F AY2 N Z",
  "adverse": "AE0 D V ER1 S",
  "mess": "M EH1 S",
  "teams": "T IY1 M Z",
  "sectors": "S EH1 K T ER0 Z",
  "ceiling": "S IY1 L IH0 NG",
  "elegance": "EH1 L AH0 G AH0 N S",
  "ant": "AE1 N T",
  "drones": "D R OW1 N Z",
  "friction": "F R IH1 K SH AH0 N",
  "ideology": "AY2 D IY0 AA1 L AH0 JH IY0",
  "morals": "M AO1 R AH0 L Z",
  "subservience": "S AH0 B S ER1 V IY0 AH0 N S",
  "battle": "B AE1 T AH0 L",
  "sedition": "S IH0 D IH1 SH AH0 N",
  "ingrained": "IH2 N G R EY1 N D",
  "fruit": "F R UW1 T",
  "guessing": "G EH1 S IH0 NG",
  "malpractice": "M AE0 L P R AE1 K T AH0 S",
  "elope": "IH0 L OW1 P",
  "see": "S IY1",
  "horizon": "HH ER0 AY1 Z AH0 N",
  "entropy": "EH1 N T R AH0 P IY0",
  "tangible": "T AE1 N JH AH0 B AH0 L",
  "horse": "HH AO1 R S",
  "references": "R EH1 F ER0 AH0 N S IH0 Z",
  "slate": "S L EY1 T",
  "concealing": "K AH0 N S IY1 L IH0 NG",
  "versions": "V ER1 ZH AH0 N Z",
  "measurements": "M EH1 ZH ER0 M AH0 N T S",
  "unrestrained": "AH2 N R IY0 S T R EY1 N D",
  "round": "R AW1 N D",
  "consistently": "K AH0 N S IH1 S T AH0 N T L IY0",
  "rivalry": "R AY1 V AH0 L R IY0",
  "schisms": "S K IH1 Z AH0 M Z",
  "remorse": "R IH0 M AO1 R S",
  "sanity": "S AE1 N AH0 T IY0",
  "list": "L IH1 S T",
  "fuckers": "F AH1 K ER0 Z",
  "based": "B EY1 S T",
  "overload": "OW1 V ER0 L OW2 D",
  "pray": "P R EY1",
  "plan": "P L AE1 N",
  "goings": "G OW1 IH0 NG Z",
  "dealt": "D EH1 L T",
  "recursive": "R IY2 K ER1 S IH0 V",
  "slated": "S L EY1 T IH0 D",
  "thing": "TH IH1 NG",
  "cycle": "S AY1 K AH0 L",
  "marked": "M AA1 R K T",
  "everyday": "EH1 V R IY0 D EY1",
  "miles": "M AY1 L Z",
  "implications": "IH2 M P L AH0 K EY1 SH AH0 N Z",
  "pharaohs": "F EH1 R OW0 Z",
  "case": "K EY1 S",
  "consequence": "K AA1 N S AH0 K W AH0 N S",
  "lives": "L IH1 V Z",
  "pieces": "P IY1 S AH0 Z",
  "suspended": "S AH0 S P EH1 N D IH0 D",
  "finalized": "F AY1 N AH0 L AY2 Z D",
  "imagination": "IH2 M AE2 JH AH0 N EY1 SH AH0 N",
  "difficult": "D IH1 F AH0 K AH0 L T",
  "deplete": "D IH0 P L IY1 T",
  "inputs": "IH1 N P UH2 T S",
  "lowest": "L OW1 AH0 S T",
  "upon": "AH0 P AA1 N",
  "investments": "IH2 N V EH1 S T M AH0 N T S",
  "terminal": "T ER1 M IH0 N AH0 L",
  "avoid": "AH0 V OY1 D",
  "fumes": "F Y UW1 M Z",
  "outdated": "AW1 T D EY2 T IH0 D",
  "denominator": "D IH0 N AA1 M AH0 N EY2 T ER0",
  "lack": "L AE1 K",
  "interlopers": "IH1 N T ER0 L OW2 P ER0 Z",
  "imperative": "IH2 M P EH1 R AH0 T IH0 V",
  "infantry": "IH1 N F AH0 N T R IY0",
  "times": "T AY1 M Z",
  "manage": "M AE1 N AH0 JH",
  "music": "M Y UW1 Z IH0 K",
  "flows": "F L OW1 Z",
  "metrics": "M EH1 T R IH0 K S",
  "bones": "B OW1 N Z",
  "tries": "T R AY1 Z",
  "embracing": "EH0 M B R EY1 S IH0 NG",
  "refinement": "R AH0 F AY1 N M AH0 N T",
  "interests": "IH1 N T R AH0 S T S",
  "worse": "W ER1 S",
  "perpetuated": "P ER0 P EH1 CH AH0 W EY2 T IH0 D",
  "sage": "S EY1 JH",
  "lad": "L AE1 D",
  "integration": "IH2 N T AH0 G R EY1 SH AH0 N",
  "honest": "AA1 N AH0 S T",
  "question": "K W EH1 S CH AH0 N",
  "pause": "P AO1 Z",
  "cruel": "K R UW1 AH0 L",
  "threat": "TH R EH1 T",
  "defined": "D IH0 F AY1 N D",
  "erased": "IH0 R EY1 S T",
  "flaws": "F L AO1 Z",
  "aggression": "AH0 G R EH1 SH AH0 N",
  "couple": "K AH1 P AH0 L",
  "broken": "B R OW1 K AH0 N",
  "utility": "Y UW0 T IH1 L AH0 T IY0",
  "bombs": "B AA1 M Z",
  "wars": "W AO1 R Z",
  "feed": "F IY1 D",
  "dividends": "D IH1 V IH0 D EH2 N D Z",
  "applied": "AH0 P L AY1 D",
  "supported": "S AH0 P AO1 R T IH0 D",
  "conflicted": "K AH0 N F L IH1 K T IH0 D",
  "equations": "IH0 K W EY1 ZH AH0 N Z",
  "fly": "F L AY1",
  "somethings": "S AH1 M TH IH2 NG Z",
  "enter": "EH1 N T ER0",
  "mainframe": "M EY1 N F R EY2 M",
  "living": "L IH1 V IH0 NG",
  "draw": "D R AO1",
  "philanthropy": "F IH0 L AE1 N TH R AH0 P IY0",
  "ordeal": "AO0 R D IY1 L",
  "intact": "IH2 N T AE1 K T",
  "fabricated": "F AE1 B R IH0 K EY2 T AH0 D",
  "crafts": "K R AE1 F T S",
  "crooked": "K R UH1 K AH0 D",
  "tempted": "T EH1 M P T IH0 D",
  "flesh": "F L EH1 SH",
  "fine": "F AY1 N",
  "below": "B IH0 L OW1",
  "sent": "S EH1 N T",
  "needed": "N IY1 D AH0 D",
  "hindrance": "HH IH1 N D R AH0 N S",
  "glass": "G L AE1 S",
  "percent": "P ER0 S EH1 N T",
  "nervous": "N ER1 V AH0 S",
  "concern": "K AH0 N S ER1 N",
  "longer": "L AO1 NG G ER0",
  "mans": "M AE1 N Z",
  "loss": "L AO1 S",
  "relate": "R IH0 L EY1 T",
  "choke": "CH OW1 K",
  "unsteady": "AH0 N S T EH1 D IY0",
  "intervenes": "IH2 N T ER0 V IY1 N Z",
  "reveal": "R IH0 V IY1 L",
  "flask": "F L AE1 S K",
  "desk": "D EH1 S K",
  "incentives": "IH2 N S EH1 N T IH0 V Z",
  "beauty": "B Y UW1 T IY0",
  "lyrics": "L IH1 R IH0 K S",
  "tribal": "T R AY1 B AH0 L",
  "neighbor": "N EY1 B ER0",
  "cruelest": "K R UW1 L AH0 S T",
  "great": "G R EY1 T",
  "ignorance": "IH1 G N ER0 AH0 N S",
  "unrefined": "AH2 N R IY0 F AY1 N D",
  "miss": "M IH1 S",
  "mustang": "M AH1 S T AE2 NG",
  "thrives": "TH R AY1 V Z",
  "numb": "N AH1 M",
  "liberation": "L IH2 B ER2 EY1 SH AH0 N",
  "action": "AE1 K SH AH0 N",
  "ash": "AE1 SH",
  "crawl": "K R AO1 L",
  "fair": "F EH1 R",
  "tonics": "T AA1 N IH0 K S",
  "baseless": "B EY1 S L AH0 S",
  "pleasant": "P L EH1 Z AH0 N T",
  "weather": "W EH1 DH ER0",
  "sight": "S AY1 T",
  "talking": "T AO1 K IH0 NG",
  "conflate": "K AH0 N F L EY1 T",
  "patient": "P EY1 SH AH0 N T",
  "mental": "M EH1 N T AH0 L",
  "blame": "B L EY1 M",
  "liege": "L IY1 JH",
  "evil": "IY1 V AH0 L",
  "awareness": "AH0 W EH1 R N AH0 S",
  "prone": "P R OW1 N",
  "hat": "HH AE1 T",
  "core": "K AO1 R",
  "beams": "B IY1 M Z",
  "mind": "M AY1 N D",
  "social": "S OW1 SH AH0 L",
  "dark": "D AA1 R K",
  "new": "N UW1",
  "provisions": "P R AH0 V IH1 ZH AH0 N Z",
  "narrow": "N EH1 R OW0",
  "unknown": "AH0 N N OW1 N",
  "consensus": "K AH0 N S EH1 N S AH0 S",
  "high": "HH AY1",
  "baffle": "B AE1 F AH0 L",
  "innovations": "IH2 N AH0 V EY1 SH AH0 N Z",
  "combustion": "K AH0 M B AH1 S CH AH0 N",
  "grip": "G R IH1 P",
  "skill": "S K IH1 L",
  "ascended": "AH0 S EH1 N D IH0 D",
  "dominant": "D AA1 M AH0 N AH0 N T",
  "flock": "F L AA1 K",
  "replete": "R IY0 P L IY1 T",
  "hero": "HH IH1 R OW0",
  "explode": "IH0 K S P L OW1 D",
  "america": "AH0 M EH1 R IH0 K AH0",
  "smack": "S M AE1 K",
  "persist": "P ER0 S IH1 S T",
  "protect": "P R AH0 T EH1 K T",
  "deficit": "D EH1 F AH0 S AH0 T",
  "displacement": "D IH0 S P L EY1 S M AH0 N T",
  "supersonic": "S UW2 P ER0 S AA1 N IH0 K",
  "forlorn": "F ER0 L AO1 R N",
  "ascend": "AH0 S EH1 N D",
  "encoded": "EH0 N K OW1 D IH0 D",
  "conflicting": "K AH0 N F L IH1 K T IH0 NG",
  "known": "N OW1 N",
  "enabled": "EH0 N EY1 B AH0 L D",
  "expect": "IH0 K S P EH1 K T",
  "relax": "R IH0 L AE1 K S",
  "drawing": "D R AO1 IH0 NG",
  "share": "SH EH1 R",
  "overdose": "OW1 V ER0 D OW2 S",
  "creation": "K R IY0 EY1 SH AH0 N",
  "research": "R IY0 S ER1 CH",
  "prisons": "P R IH1 Z AH0 N Z",
  "ahead": "AH0 HH EH1 D",
  "consuming": "K AH0 N S UW1 M IH0 NG",
  "behavior": "B IH0 HH EY1 V Y ER0",
  "manner": "M AE1 N ER0",
  "retrograde": "R EH1 T R AH0 G R EY2 D",
  "follow": "F AA1 L OW0",
  "somehow": "S AH1 M HH AW2",
  "twin": "T W IH1 N",
  "star": "S T AA1 R",
  "anointed": "AH0 N OY1 N T IH0 D",
  "guide": "G AY1 D",
  "flame": "F L EY1 M",
  "growth": "G R OW1 TH",
  "thought": "TH AO1 T",
  "enforced": "EH0 N F AO1 R S T",
  "iced": "AY1 S T",
  "doc": "D AA1 K",
  "consume": "K AH0 N S UW1 M",
  "abyss": "AH0 B IH1 S",
  "caught": "K AA1 T",
  "civilization": "S IH2 V AH0 L IH0 Z EY1 SH AH0 N",
  "implore": "IH2 M P L AO1 R",
  "misbehavior": "M IH2 S B AH0 HH EY1 V Y ER0",
  "morn": "M AO1 R N",
  "enacted": "EH0 N AE1 K T AH0 D",
  "boom": "B UW1 M",
  "bent": "B EH1 N T",
  "po": "P OW1",
  "flounder": "F L AW1 N D ER0",
  "earths": "ER1 TH S",
  "fingertips": "F IH1 NG G ER0 T IH2 P S",
  "mentally": "M EH1 N T AH0 L IY0",
  "observation": "AA2 B Z ER0 V EY1 SH AH0 N",
  "sins": "S IH1 N Z",
  "storm": "S T AO1 R M",
  "else": "EH1 L S",
  "darkness": "D AA1 R K N AH0 S",
  "common": "K AA1 M AH0 N",
  "clipboard": "K L IH1 P B AO2 R D",
  "statistic": "S T AH0 T IH1 S T IH0 K",
  "explicit": "IH0 K S P L IH1 S AH0 T",
  "care": "K EH1 R",
  "tail": "T EY1 L",
  "seams": "S IY1 M Z",
  "believe": "B IH0 L IY1 V",
  "chasing": "CH EY1 S IH0 NG",
  "preserve": "P R AH0 Z ER1 V",
  "primates": "P R AY1 M EY2 T S",
  "bold": "B OW1 L D",
  "savage": "S AE1 V AH0 JH",
  "allegiance": "AH0 L IY1 JH AH0 N S",
  "regardless": "R AH0 G AA1 R D L AH0 S",
  "warped": "W AO1 R P T",
  "clarity": "K L EH1 R AH0 T IY0",
  "sergeant": "S AA1 R JH AH0 N T",
  "physically": "F IH1 Z IH0 K AH0 L IY0",
  "movement": "M UW1 V M AH0 N T",
  "vestigial": "V AH0 S T IH1 JH IY0 AH0 L",
  "lady": "L EY1 D IY0",
  "cloak": "K L OW1 K",
  "schism": "S K IH1 Z AH0 M",
  "circumvent": "S ER2 K AH0 M V EH1 N T",
  "agreements": "AH0 G R IY1 M AH0 N T S",
  "lethargy": "L EH1 TH ER0 JH IY0",
  "precision": "P R IY0 S IH1 ZH AH0 N",
  "genetic": "JH AH0 N EH1 T IH0 K",
  "bridge": "B R IH1 JH",
  "breathe": "B R IY1 DH",
  "fraught": "F R AO1 T",
  "hearts": "HH AA1 R T S",
  "respect": "R IH0 S P EH1 K T",
  "incision": "IH2 N S IH1 ZH AH0 N",
  "en": "EH1 N",
  "reactor": "R IY0 AE1 K T ER0",
  "equal": "IY1 K W AH0 L",
  "lit": "L IH1 T",
  "transformation": "T R AE2 N S F ER0 M EY1 SH AH0 N",
  "sick": "S IH1 K",
  "beach": "B IY1 CH",
  "evidently": "EH1 V AH0 D AH0 N T L IY0",
  "behave": "B IH0 HH EY1 V",
  "demented": "D IH0 M EH1 N T IH0 D",
  "persists": "P ER0 S IH1 S T S",
  "innovator": "IH1 N AH0 V EY2 T ER0",
  "sects": "S EH1 K T S",
  "stood": "S T UH1 D",
  "chain": "CH EY1 N",
  "flares": "F L EH1 R Z",
  "years": "Y IH1 R Z",
  "planet": "P L AE1 N AH0 T",
  "ten": "T EH1 N",
  "fiend": "F IY1 N D",
  "debts": "D EH1 T S",
  "sell": "S EH1 L",
  "sermons": "S ER1 M AH0 N Z",
  "wield": "W IY1 L D",
  "narrative": "N AE1 R AH0 T IH0 V",
  "born": "B AO1 R N",
  "grind": "G R AY1 N D",
  "once": "W AH1 N S",
  "learn": "L ER1 N",
  "lunge": "L AH1 N JH",
  "blessing": "B L EH1 S IH0 NG",
  "annals": "AE1 N AH0 L Z",
  "decommission": "D IY0 K AH0 M IH1 SH AH0 N",
  "audits": "AA1 D AH0 T S",
  "enforcing": "EH0 N F AO1 R S IH0 NG",
  "heavy": "HH EH1 V IY0",
  "tortured": "T AO1 R CH ER0 D",
  "zeitgeist": "T S AY1 T G AY2 S T",
  "deviant": "D IY1 V IY0 AH0 N T",
  "improper": "IH2 M P R AA1 P ER0",
  "insincere": "IH2 N S IH0 N S IH1 R",
  "flames": "F L EY1 M Z",
  "darkest": "D AA1 R K AH0 S T",
  "slow": "S L OW1",
  "genesis": "JH EH1 N AH0 S AH0 S",
  "bias": "B AY1 AH0 S",
  "array": "ER0 EY1",
  "em": "EH1 M",
  "elitist": "EY0 L IY1 T IH0 S T",
  "pot": "P AA1 T",
  "communicate": "K AH0 M Y UW1 N AH0 K EY2 T",
  "passion": "P AE1 SH AH0 N",
  "try": "T R AY1",
  "another": "AH0 N AH1 DH ER0",
  "hits": "HH IH1 T S",
  "grown": "G R OW1 N",
  "makin": "M AE1 K IH0 N",
  "stretch": "S T R EH1 CH",
  "escaped": "IH0 S K EY1 P T",
  "tragedy": "T R AE1 JH AH0 D IY0",
  "kingdom": "K IH1 NG D AH0 M",
  "resistance": "R IH0 Z IH1 S T AH0 N S",
  "pressed": "P R EH1 S T",
  "hang": "HH AE1 NG",
  "nations": "N EY1 SH AH0 N Z",
  "current": "K ER1 AH0 N T",
  "ventilation": "V EH2 N T IH0 L EY1 SH AH0 N",
  "extremist": "IH0 K S T R IY1 M IH0 S T",
  "proximity": "P R AA0 K S IH1 M AH0 T IY0",
  "eminent": "EH1 M AH0 N AH0 N T",
  "state": "S T EY1 T",
  "thinking": "TH IH1 NG K IH0 NG",
  "division": "D IH0 V IH1 ZH AH0 N",
  "mezzanine": "M EH1 Z AH0 N IY2 N",
  "human": "HH Y UW1 M AH0 N",
  "enlisted": "EH2 N L IH1 S T IH0 D",
  "feat": "F IY1 T",
  "selfish": "S EH1 L F IH0 SH",
  "views": "V Y UW1 Z",
  "efficient": "IH0 F IH1 SH AH0 N T",
  "race": "R EY1 S",
  "walk": "W AO1 K",
  "makes": "M EY1 K S",
  "effortlessly": "EH1 F ER0 T L AH0 S L IY0",
  "fascination": "F AE2 S AH0 N EY1 SH AH0 N",
  "prophecy": "P R AA1 F AH0 S IY0",
  "influence": "IH1 N F L UW0 AH0 N S",
  "movements": "M UW1 V M AH0 N T S",
  "exits": "EH1 G Z IH0 T S",
  "emboldened": "EH0 M B OW1 L D AH0 N D",
  "correct": "K ER0 EH1 K T",
  "flooded": "F L AH1 D AH0 D",
  "area": "EH1 R IY0 AH0",
  "notion": "N OW1 SH AH0 N",
  "hyperdrive": "HH AY1 P ER0 D R AY2 V",
  "conceptually": "K AH0 N S EH1 P CH UW0 AH0 L IY0",
  "curved": "K ER1 V D",
  "dimensions": "D IH0 M EH1 N SH AH0 N Z",
  "admission": "AE0 D M IH1 SH AH0 N",
  "thirsting": "TH ER1 S T IH0 NG",
  "existed": "IH0 G Z IH1 S T AH0 D",
  "released": "R IY0 L IY1 S T",
  "chaos": "K EY1 AA0 S",
  "fleece": "F L IY1 S",
  "ideally": "AY0 D IY1 L IY0",
  "unconscious": "AH2 N K AA1 N SH AH0 S",
  "veterans": "V EH1 T ER0 AH0 N Z",
  "trace": "T R EY1 S",
  "impatient": "IH2 M P EY1 SH AH0 N T",
  "serpent": "S ER1 P AH0 N T",
  "corporations": "K AO2 R P ER0 EY1 SH AH0 N Z",
  "practice": "P R AE1 K T IH0 S",
  "graphic": "G R AE1 F IH0 K",
  "dopamine": "D AA1 P AH0 M AY2 N",
  "sticks": "S T IH1 K S",
  "clocks": "K L AA1 K S",
  "chimera": "CH IH0 M EH1 R AH0",
  "cream": "K R IY1 M",
  "controlled": "K AH0 N T R OW1 L D",
  "dose": "D OW1 S",
  "false": "F AO1 L S",
  "inept": "IH2 N EH1 P T",
  "peons": "P IY1 AH0 N Z",
  "spite": "S P AY1 T",
  "blurred": "B L ER1 D",
  "blue": "B L UW1",
  "primers": "P R AY1 M ER0 Z",
  "switch": "S W IH1 CH",
  "pen": "P EH1 N",
  "aligned": "AH0 L AY1 N D",
  "feeling": "F IY1 L IH0 NG",
  "override": "OW1 V ER0 R AY2 D",
  "whirlpool": "W ER1 L P UW2 L",
  "seek": "S IY1 K",
  "rabid": "R AE1 B IH0 D",
  "waste": "W EY1 S T",
  "evasive": "IH0 V EY1 Z IH0 V",
  "accepted": "AE0 K S EH1 P T IH0 D",
  "mission": "M IH1 SH AH0 N",
  "repeat": "R IH0 P IY1 T",
  "hate": "HH EY1 T",
  "orbit": "AO1 R B AH0 T",
  "forts": "F AO1 R T S",
  "collapse": "K AH0 L AE1 P S",
  "taste": "T EY1 S T",
  "stance": "S T AE1 N S",
  "isolation": "AY2 S AH0 L EY1 SH AH0 N",
  "stupid": "S T UW1 P IH0 D",
  "seat": "S IY1 T",
  "impedes": "IH2 M P IY1 D Z",
  "engraved": "IH0 N G R EY1 V D",
  "baby": "B EY1 B IY0",
  "history": "HH IH1 S T ER0 IY0",
  "console": "K AA1 N S OW0 L",
  "absurd": "AH0 B S ER1 D",
  "awfully": "AO1 F AH0 L IY0",
  "mist": "M IH1 S T",
  "formulate": "F AO1 R M Y AH0 L EY2 T",
  "advantages": "AE0 D V AE1 N T IH0 JH IH0 Z",
  "surpass": "S ER0 P AE1 S",
  "necessary": "N EH1 S AH0 S EH2 R IY0",
  "robbery": "R AA1 B ER0 IY0",
  "emerald": "EH1 M R AH0 L D",
  "impervious": "IH2 M P ER1 V IY0 AH0 S",
  "lie": "L AY1",
  "attempt": "AH0 T EH1 M P T",
  "battlements": "B AE1 T AH0 L M AH0 N T S",
  "service": "S ER1 V AH0 S",
  "jaded": "JH EY1 D AH0 D",
  "inconsistent": "IH2 N K AH0 N S IH1 S T AH0 N T",
  "rather": "R AE1 DH ER0",
  "info": "IH1 N F OW0",
  "optimize": "AA1 P T IH0 M AY2 Z",
  "embolden": "EH0 M B OW1 L D AH0 N",
  "conversation": "K AA2 N V ER0 S EY1 SH AH0 N",
  "beacon": "B IY1 K AH0 N",
  "eyesight": "AY1 S AY2 T",
  "wake": "W EY1 K",
  "trite": "T R AY1 T",
  "depend": "D IH0 P EH1 N D",
  "slash": "S L AE1 SH",
  "combine": "K AA1 M B AY0 N",
  "schedule": "S K EH1 JH UH0 L",
  "nocturnal": "N AA0 K T ER1 N AH0 L",
  "art": "AA1 R T",
  "full": "F UH1 L",
  "stray": "S T R EY1",
  "deleted": "D IH0 L IY1 T AH0 D",
  "rate": "R EY1 T",
  "concerted": "K AH0 N S ER1 T AH0 D",
  "eras": "IH1 R AH0 Z",
  "addressing": "AE0 D R EH1 S IH0 NG",
  "cultivation": "K AH2 L T IH0 V EY1 SH AH0 N",
  "artificial": "AA2 R T AH0 F IH1 SH AH0 L",
  "saturating": "S AE1 CH ER0 EY2 T IH0 NG",
  "someday": "S AH1 M D EY2",
  "pledge": "P L EH1 JH",
  "purist": "P Y UH1 R IH0 S T",
  "disaster": "D IH0 Z AE1 S T ER0",
  "humanity": "HH Y UW0 M AE1 N IH0 T IY0",
  "reservation": "R EH2 Z ER0 V EY1 SH AH0 N",
  "crimes": "K R AY1 M Z",
  "mote": "M OW1 T",
  "fraudulent": "F R AO1 JH AH0 L AH0 N T",
  "helpless": "HH EH1 L P L AH0 S",
  "rockets": "R AA1 K AH0 T S",
  "messenger": "M EH1 S AH0 N JH ER0",
  "blind": "B L AY1 N D",
  "malfeasance": "M AE2 L F IY1 Z AH0 N S",
  "knight": "N AY1 T",
  "targets": "T AA1 R G AH0 T S",
  "playful": "P L EY1 F AH0 L",
  "schemes": "S K IY1 M Z",
  "rising": "R AY1 Z IH0 NG",
  "calculated": "K AE1 L K Y AH0 L EY2 T AH0 D",
  "zoom": "Z UW1 M",
  "text": "T EH1 K S T",
  "recipe": "R EH1 S AH0 P IY0",
  "amnesty": "AE1 M N AH0 S T IY0",
  "pointed": "P OY1 N T IH0 D",
  "cold": "K OW1 L D",
  "erasmus": "IH0 R AE1 Z M AH0 S",
  "actors": "AE1 K T ER0 Z",
  "narratives": "N AE1 R AH0 T IH0 V Z",
  "foundation": "F AW0 N D EY1 SH AH0 N",
  "rearrange": "R IY2 ER0 EY1 N JH",
  "speech": "S P IY1 CH",
  "tech": "T EH1 K",
  "setup": "S EH1 T AH2 P",
  "train": "T R EY1 N",
  "insert": "IH2 N S ER1 T",
  "scores": "S K AO1 R Z",
  "entertain": "EH2 N T ER0 T EY1 N",
  "depths": "D EH1 P TH S",
  "vengeance": "V EH1 N JH AH0 N S",
  "kinds": "K AY1 N D Z",
  "mask": "M AE1 S K",
  "brat": "B R AE1 T",
  "barks": "B AA1 R K S",
  "self": "S EH1 L F",
  "doom": "D UW1 M",
  "perspectives": "P ER0 S P EH1 K T IH0 V Z",
  "relent": "R IH0 L EH1 N T",
  "freed": "F R IY1 D",
  "grant": "G R AE1 N T",
  "casualties": "K AE1 ZH AH0 W AH0 L T IY0 Z",
  "sufficient": "S AH0 F IH1 SH AH0 N T",
  "charade": "SH ER0 EY1 D",
  "bid": "B IH1 D",
  "certain": "S ER1 T AH0 N",
  "meaning": "M IY1 N IH0 NG",
  "essence": "EH1 S AH0 N S",
  "exhume": "EH0 K S HH Y UW1 M",
  "enlighten": "EH2 N L AY1 T AH0 N",
  "serene": "S ER0 IY1 N",
  "jar": "JH AA1 R",
  "osmosis": "AO2 Z M OW1 S IH0 S",
  "merit": "M EH1 R AH0 T",
  "pyres": "P AY1 ER0 Z",
  "dare": "D EH1 R",
  "astray": "AH0 S T R EY1",
  "talkin": "T AA1 K AH0 N",
  "holds": "HH OW1 L D Z",
  "unlimited": "AH0 N L IH1 M IH0 T IH0 D",
  "dreaming": "D R IY1 M IH0 NG",
  "obsolescence": "AA2 B S AH0 L EH1 S AH0 N S",
  "transcending": "T R AE0 N S EH1 N D IH0 NG",
  "build": "B IH1 L D",
  "murals": "M Y UH1 R AH0 L Z",
  "diagnosed": "D AY2 AH0 G N OW1 S T",
  "language": "L AE1 NG G W AH0 JH",
  "glare": "G L EH1 R",
  "whether": "W EH1 DH ER0",
  "barely": "B EH1 R L IY0",
  "looking": "L UH1 K IH0 NG",
  "affirmative": "AH0 F ER1 M AH0 T IH0 V",
  "alone": "AH0 L OW1 N",
  "breath": "B R EH1 TH",
  "intake": "IH1 N T EY2 K",
  "conceived": "K AH0 N S IY1 V D",
  "either": "IY1 DH ER0",
  "even": "IY1 V IH0 N",
  "truly": "T R UW1 L IY0",
  "incessantly": "IH2 N S EH1 S AH0 N T L IY0",
  "screaming": "S K R IY1 M IH0 NG",
  "catch": "K AE1 CH",
  "disciples": "D IH0 S AY1 P AH0 L Z",
  "aversion": "AH0 V ER1 ZH AH0 N",
  "exploitation": "EH2 K S P L OY2 T EY1 SH AH0 N",
  "shit": "SH IH1 T",
  "spray": "S P R EY1",
  "devotion": "D IH0 V OW1 SH AH0 N",
  "harmed": "HH AA1 R M D",
  "mercy": "M ER1 S IY0",
  "deficient": "D IH0 F IH1 SH AH0 N T",
  "tax": "T AE1 K S",
  "seconds": "S EH1 K AH0 N D Z",
  "stealth": "S T EH1 L TH",
  "bountiful": "B AW1 N T IH0 F AH0 L",
  "transcendence": "T R AE0 N S EH1 N D AH0 N S",
  "amends": "AH0 M EH1 N D Z",
  "elevator": "EH1 L AH0 V EY2 T ER0",
  "wallabies": "W AA1 L AH0 B IY2 Z",
  "styles": "S T AY1 L Z",
  "insured": "IH2 N SH UH1 R D",
  "neural": "N UH1 R AH0 L",
  "doublethink": "D AH1 B AH0 L TH IH2 NG K",
  "indecision": "IH2 N D IH0 S IH1 ZH AH0 N",
  "nurture": "N ER1 CH ER0",
  "fueled": "F Y UW1 AH0 L D",
  "booty": "B UW1 T IY0",
  "vexed": "V EH1 K S T",
  "between": "B IH0 T W IY1 N",
  "tools": "T UW1 L Z",
  "damage": "D AE1 M AH0 JH",
  "two": "T UW1",
  "drifting": "D R IH1 F T IH0 NG",
  "egregiously": "IH0 G R IY1 JH AH0 S L IY0",
  "song": "S AO1 NG",
  "sin": "S IH1 N",
  "object": "AA1 B JH EH0 K T",
  "fit": "F IH1 T",
  "convincing": "K AH0 N V IH1 N S IH0 NG",
  "trial": "T R AY1 AH0 L",
  "teachers": "T IY1 CH ER0 Z",
  "drop": "D R AA1 P",
  "institutions": "IH2 N S T IH0 T UW1 SH AH0 N Z",
  "helped": "HH EH1 L P T",
  "map": "M AE1 P",
  "sowing": "S OW1 IH0 NG",
  "plot": "P L AA1 T",
  "unstoppable": "AH0 N S T AA1 P AH0 B AH0 L",
  "appeal": "AH0 P IY1 L",
  "mending": "M EH1 N D IH0 NG",
  "office": "AO1 F AH0 S",
  "reprieve": "R IY0 P R IY1 V",
  "emotions": "IH0 M OW1 SH AH0 N Z",
  "instead": "IH2 N S T EH1 D",
  "stagnation": "S T AE0 G N EY1 SH AH0 N",
  "stressed": "S T R EH1 S T",
  "wait": "W EY1 T",
  "patience": "P EY1 SH AH0 N S",
  "insurmountable": "IH2 N S ER0 M AW1 N T AH0 B AH0 L",
  "imprisonment": "IH2 M P R IH1 Z AH0 N M AH0 N T",
  "enemies": "EH1 N AH0 M IY0 Z",
  "serenity": "S ER0 EH1 N AH0 T IY0",
  "tomes": "T OW1 M Z",
  "manor": "M AE1 N ER0",
  "misplaced": "M IH0 S P L EY1 S T",
  "robotics": "R OW2 B AA1 T IH0 K S",
  "inflation": "IH2 N F L EY1 SH AH0 N",
  "serving": "S ER1 V IH0 NG",
  "inhabited": "IH2 N HH AE1 B AH0 T AH0 D",
  "works": "W ER1 K S",
  "curse": "K ER1 S",
  "undiscovered": "AH2 N D IH0 S K AH1 V ER0 D",
  "chemistry": "K EH1 M IH0 S T R IY0",
  "groove": "G R UW1 V",
  "steelman": "S T IY1 L M AH0 N",
  "death": "D EH1 TH",
  "people": "P IY1 P AH0 L",
  "trust": "T R AH1 S T",
  "bank": "B AE1 NG K",
  "concrete": "K AH0 N K R IY1 T",
  "drained": "D R EY1 N D",
  "led": "L EH1 D",
  "need": "N IY1 D",
  "latent": "L EY1 T AH0 N T",
  "held": "HH EH1 L D",
  "bomb": "B AA1 M",
  "hordes": "HH AO1 R D Z",
  "savior": "S EY1 V Y ER0",
  "matters": "M AE1 T ER0 Z",
  "unscathed": "AH0 N S K EY1 DH D",
  "anarchy": "AE1 N ER0 K IY2",
  "waist": "W EY1 S T",
  "howl": "HH AW1 L",
  "revert": "R IH0 V ER1 T",
  "silence": "S AY1 L AH0 N S",
  "catalyst": "K AE1 T AH0 L IH2 S T",
  "beasts": "B IY1 S T S",
  "usual": "Y UW1 ZH AH0 W AH0 L",
  "fault": "F AO1 L T",
  "republics": "R IY0 P AH1 B L IH0 K S",
  "settle": "S EH1 T AH0 L",
  "performance": "P ER0 F AO1 R M AH0 N S",
  "stand": "S T AE1 N D",
  "failed": "F EY1 L D",
  "anyways": "EH1 N IY0 W EY2 Z",
  "whats": "W AH0 T S",
  "swing": "S W IH1 NG",
  "accumulated": "AH0 K Y UW1 M Y AH0 L EY2 T IH0 D",
  "suppressing": "S AH0 P R EH1 S IH0 NG",
  "release": "R IY0 L IY1 S",
  "meek": "M IY1 K",
  "holy": "HH OW1 L IY0",
  "orifice": "AO1 R AH0 F AH0 S",
  "compulsive": "K AH0 M P AH1 L S IH0 V",
  "emergence": "IH0 M ER1 JH AH0 N S",
  "sweaty": "S W EH1 T IY0",
  "different": "D IH1 F ER0 AH0 N T",
  "leveraging": "L EH1 V R IH0 JH IH0 NG",
  "path": "P AE1 TH",
  "retain": "R IH0 T EY1 N",
  "cope": "K OW1 P",
  "content": "K AA1 N T EH0 N T",
  "fist": "F IH1 S T",
  "centuries": "S EH1 N CH ER0 IY0 Z",
  "bliss": "B L IH1 S",
  "conductive": "K AH0 N D AH1 K T IH0 V",
  "duel": "D UW1 AH0 L",
  "everything": "EH1 V R IY0 TH IH2 NG",
  "consumed": "K AH0 N S UW1 M D",
  "canvas": "K AE1 N V AH0 S",
  "variables": "V EH1 R IY0 AH0 B AH0 L Z",
  "bounce": "B AW1 N S",
  "teach": "T IY1 CH",
  "mortar": "M AO1 R T ER0",
  "way": "W EY1",
  "furthest": "F ER1 TH AH0 S T",
  "exert": "IH0 G Z ER1 T",
  "apart": "AH0 P AA1 R T",
  "defect": "D IY1 F EH0 K T",
  "without": "W IH0 TH AW1 T",
  "atomic": "AH0 T AA1 M IH0 K",
  "phylum": "F AY1 L AH0 M",
  "machine": "M AH0 SH IY1 N",
  "class": "K L AE1 S",
  "opportunities": "AA2 P ER0 T UW1 N AH0 T IY0 Z",
  "nation": "N EY1 SH AH0 N",
  "dreams": "D R IY1 M Z",
  "rages": "R EY1 JH IH0 Z",
  "gears": "G IH1 R Z",
  "foundations": "F AW0 N D EY1 SH AH0 N Z",
  "savagery": "S AE1 V IH0 JH EH2 R IY0",
  "unite": "Y UW1 N AY2 T",
  "birds": "B ER1 D Z",
  "ta": "T AA1",
  "nicotine": "N IH1 K AH0 T IY2 N",
  "lame": "L EY1 M",
  "math": "M AE1 TH",
  "right": "R AY1 T",
  "nothing": "N AH1 TH IH0 NG",
  "dance": "D AE1 N S",
  "wind": "W AY1 N D",
  "survive": "S ER0 V AY1 V",
  "levels": "L EH1 V AH0 L Z",
  "concealed": "K AH0 N S IY1 L D",
  "bove": "B OW1 V",
  "currency": "K ER1 AH0 N S IY0",
  "backs": "B AE1 K S",
  "presence": "P R EH1 Z AH0 N S",
  "vermin": "V ER1 M IH0 N",
  "ostentatiously": "AA2 S T AH0 N T EY1 SH AH0 S L IY0",
  "word": "W ER1 D",
  "wisdom": "W IH1 Z D AH0 M",
  "fate": "F EY1 T",
  "distributed": "D IH0 S T R IH1 B Y AH0 T AH0 D",
  "decisions": "D IH0 S IH1 ZH AH0 N Z",
  "soliloquy": "S AH0 L IH1 L AH0 K W IY0",
  "composed": "K AH0 M P OW1 Z D",
  "effortless": "EH1 F ER0 T L AH0 S",
  "enthralled": "EH0 N TH R AO1 L D",
  "things": "TH IH1 NG Z",
  "intelligence": "IH2 N T EH1 L AH0 JH AH0 N S",
  "dash": "D AE1 SH",
  "ruse": "R UW1 Z",
  "freeform": "F R IY1 F AO2 R M",
  "flip": "F L IH1 P",
  "extreme": "IH0 K S T R IY1 M",
  "cynicism": "S IH1 N IH0 S IH2 Z AH0 M",
  "moving": "M UW1 V IH0 NG",
  "existence": "EH0 G Z IH1 S T AH0 N S",
  "expressed": "IH0 K S P R EH1 S T",
  "volatile": "V AA1 L AH0 T AH0 L",
  "ruin": "R UW1 AH0 N",
  "firepower": "F AY1 R P AW2 ER0",
  "possible": "P AA1 S AH0 B AH0 L",
  "linguistics": "L IH0 NG G W IH1 S T IH0 K S",
  "step": "S T EH1 P",
  "grand": "G R AE1 N D",
  "react": "R IY0 AE1 K T",
  "conceal": "K AH0 N S IY1 L",
  "reason": "R IY1 Z AH0 N",
  "cyber": "S AY1 B ER0",
  "dissipate": "D IH1 S AH0 P EY2 T",
  "renditions": "R EH0 N D IH1 SH AH0 N Z",
  "spread": "S P R EH1 D",
  "immerse": "IH2 M ER1 S",
  "fanatics": "F AH0 N AE1 T IH0 K S",
  "forbidden": "F AO1 R B IH0 D AH0 N",
  "air": "EH1 R",
  "moment": "M OW1 M AH0 N T",
  "children": "CH IH1 L D R AH0 N",
  "lapsed": "L AE1 P S T",
  "innate": "IH2 N EY1 T",
  "imbued": "IH2 M B Y UW1 D",
  "tolerance": "T AA1 L ER0 AH0 N S",
  "lords": "L AO1 R D Z",
  "comatose": "K OW1 M AH0 T OW2 S",
  "visage": "V IH1 Z AH0 JH",
  "seeks": "S IY1 K S",
  "beast": "B IY1 S T",
  "motley": "M AA1 T L IY0",
  "atoms": "AE1 T AH0 M Z",
  "squabble": "S K W AA1 B AH0 L",
  "gremlin": "G R EH1 M L AH0 N",
  "interspersed": "IH2 N T ER0 S P ER1 S T",
  "creator": "K R IY0 EY1 T ER0",
  "blabber": "B L AE1 B ER0",
  "chase": "CH EY1 S",
  "notes": "N OW1 T S",
  "shouting": "SH AW1 T IH0 NG",
  "falter": "F AO1 L T ER0",
  "biology": "B AY0 AA1 L AH0 JH IY0",
  "praise": "P R EY1 Z",
  "delivered": "D IH0 L IH1 V ER0 D",
  "bets": "B EH1 T S",
  "asimov": "AE1 S IH0 M AA0 V",
  "burns": "B ER1 N Z",
  "depression": "D IH0 P R EH1 SH AH0 N",
  "shaped": "SH EY1 P T",
  "combust": "K AH0 M B AH1 S T",
  "bars": "B AA1 R Z",
  "information": "IH2 N F AO2 R M EY1 SH AH0 N",
  "shared": "SH EH1 R D",
  "blades": "B L EY1 D Z",
  "empathy": "EH1 M P AH0 TH IY0",
  "form": "F AO1 R M",
  "enormity": "IH0 N AO1 R M AH0 T IY0",
  "tight": "T AY1 T",
  "aye": "AY1",
  "inner": "IH1 N ER0",
  "clears": "K L IH1 R Z",
  "primal": "P R AY1 M AH0 L",
  "ruptured": "R AH1 P CH ER0 D",
  "habitats": "HH AE1 B AH0 T AE2 T S",
  "exact": "IH0 G Z AE1 K T",
  "decreasing": "D IH0 K R IY1 S IH0 NG",
  "decay": "D IH0 K EY1",
  "person": "P ER1 S AH0 N",
  "ignoble": "IH2 G N OW1 B AH0 L",
  "job": "JH AA1 B",
  "replaced": "R IY2 P L EY1 S T",
  "delete": "D IH0 L IY1 T",
  "tragic": "T R AE1 JH IH0 K",
  "tranquility": "T R AE0 NG K W IH1 L IH0 T IY0",
  "fold": "F OW1 L D",
  "endeavors": "IH0 N D EH1 V ER0 Z",
  "classes": "K L AE1 S AH0 Z",
  "operations": "AA2 P ER0 EY1 SH AH0 N Z",
  "woe": "W OW1",
  "traction": "T R AE1 K SH AH0 N",
  "sweep": "S W IY1 P",
  "off": "AO1 F",
  "pinnacle": "P IH1 N AH0 K AH0 L",
  "completes": "K AH0 M P L IY1 T S",
  "rest": "R EH1 S T",
  "highway": "HH AY1 W EY2",
  "stare": "S T EH1 R",
  "dream": "D R IY1 M",
  "defacing": "D IH0 F EY1 S IH0 NG",
  "complete": "K AH0 M P L IY1 T",
  "virility": "V ER0 IH1 L AH0 T IY0",
  "masses": "M AE1 S AH0 Z",
  "big": "B IH1 G",
  "hindsight": "HH AY1 N D S AY2 T",
  "given": "G IH1 V AH0 N",
  "contender": "K AH0 N T EH1 N D ER0",
  "pacing": "P EY1 S IH0 NG",
  "provided": "P R AH0 V AY1 D IH0 D",
  "temporal": "T EH1 M P ER0 AH0 L",
  "part": "P AA1 R T",
  "throw": "TH R OW1",
  "food": "F UW1 D",
  "stability": "S T AH0 B IH1 L IH0 T IY0",
  "hedge": "HH EH1 JH",
  "efforts": "EH1 F ER0 T S",
  "gaps": "G AE1 P S",
  "existential": "EH2 G Z IH2 S T EH1 N SH AH0 L",
  "delayed": "D IH0 L EY1 D",
  "compelled": "K AH0 M P EH1 L D",
  "victim": "V IH1 K T IH0 M",
  "saved": "S EY1 V D",
  "gun": "G AH1 N",
  "sharp": "SH AA1 R P",
  "include": "IH2 N K L UW1 D",
  "holistic": "HH OW0 L IH1 S T IH0 K",
  "hiro": "HH IH1 R OW0",
  "comments": "K AA1 M EH0 N T S",
  "basic": "B EY1 S IH0 K",
  "whys": "W AY1 Z",
  "listen": "L IH1 S AH0 N",
  "methodology": "M EH2 TH AH0 D AA1 L AH0 JH IY0",
  "grassy": "G R AE1 S IY0",
  "magnanimous": "M AE0 G N AE1 N AH0 M AH0 S",
  "debased": "D AH0 B EY1 S T",
  "infinity": "IH2 N F IH1 N IH0 T IY0",
  "communion": "K AH0 M Y UW1 N Y AH0 N",
  "bestowed": "B IH0 S T OW1 D",
  "awake": "AH0 W EY1 K",
  "concurrent": "K AH0 N K ER1 AH0 N T",
  "proud": "P R AW1 D",
  "created": "K R IY0 EY1 T AH0 D",
  "poetry": "P OW1 AH0 T R IY0",
  "magic": "M AE1 JH IH0 K",
  "clashing": "K L AE1 SH IH0 NG",
  "position": "P AH0 Z IH1 SH AH0 N",
  "consumption": "K AH0 N S AH1 M P SH AH0 N",
  "thoughts": "TH AO1 T S",
  "bless": "B L EH1 S",
  "imbed": "IH0 M B EH1 D",
  "reject": "R IH0 JH EH1 K T",
  "bastards": "B AE1 S T ER0 D Z",
  "assigned": "AH0 S AY1 N D",
  "consistent": "K AH0 N S IH1 S T AH0 N T",
  "adapt": "AH0 D AE1 P T",
  "resting": "R EH1 S T IH0 NG",
  "songs": "S AO1 NG Z",
  "rise": "R AY1 Z",
  "gives": "G IH1 V Z",
  "rates": "R EY1 T S",
  "peace": "P IY1 S",
  "prince": "P R IH1 N S",
  "determined": "D IH0 T ER1 M AH0 N D",
  "loves": "L AH1 V Z",
  "foes": "F OW1 Z",
  "listened": "L IH1 S AH0 N D",
  "blooms": "B L UW1 M Z",
  "damned": "D AE1 M D",
  "impress": "IH2 M P R EH1 S",
  "button": "B AH1 T AH0 N",
  "consider": "K AH0 N S IH1 D ER0",
  "arise": "ER0 AY1 Z",
  "disseminated": "D IH0 S EH1 M AH0 N EY2 T AH0 D",
  "analysis": "AE0 N AE1 L IH0 S IH0 S",
  "lest": "L EH1 S T",
  "unbearably": "AH0 N B EH1 R AH0 B L IY0",
  "feel": "F IY1 L",
  "reflections": "R IH0 F L EH1 K SH AH0 N Z",
  "intellect": "IH1 N T AH0 L EH2 K T",
  "eventual": "AH0 V EH1 N CH UW0 AH0 L",
  "invasions": "IH2 N V EY1 ZH AH0 N Z",
  "space": "S P EY1 S",
  "sure": "SH UH1 R",
  "apparent": "AH0 P EH1 R AH0 N T",
  "raft": "R AE1 F T",
  "demon": "D IY1 M AH0 N",
  "encourage": "EH0 N K ER1 IH0 JH",
  "epochs": "EH1 P AH0 K S",
  "test": "T EH1 S T",
  "mediocre": "M IY2 D IY0 OW1 K ER0",
  "galore": "G AH0 L AO1 R",
  "contend": "K AH0 N T EH1 N D",
  "land": "L AE1 N D",
  "simian": "S IH1 M IY0 AH0 N",
  "betters": "B EH1 T ER0 Z",
  "bibles": "B AY1 B AH0 L Z",
  "pitfalls": "P IH1 T F AO2 L Z",
  "solutions": "S AA0 L UW1 SH AH0 N Z",
  "examiner": "IH0 G Z AE1 M AH0 N ER0",
  "equation": "IH0 K W EY1 ZH AH0 N",
  "store": "S T AO1 R",
  "inscriptions": "IH2 N S K R IH1 P SH AH0 N Z",
  "repair": "R IH0 P EH1 R",
  "generational": "JH EH2 N ER0 EY1 SH AH0 N AH0 L",
  "rabbits": "R AE1 B AH0 T S",
  "hammer": "HH AE1 M ER0",
  "damn": "D AE1 M",
  "sanctuary": "S AE1 NG K CH UW0 EH2 R IY0",
  "redefine": "R IY0 D IH0 F AY1 N",
  "diminish": "D IH0 M IH1 N IH0 SH",
  "nuanced": "N UW1 AA0 N S T",
  "bazooka": "B AH0 Z UW1 K AH0",
  "intentions": "IH2 N T EH1 N CH AH0 N Z",
  "calm": "K AA1 M",
  "hit": "HH IH1 T",
  "fathom": "F AE1 DH AH0 M",
  "willing": "W IH1 L IH0 NG",
  "flagrant": "F L EY1 G R AH0 N T",
  "mold": "M OW1 L D",
  "deliver": "D IH0 L IH1 V ER0",
  "dysfunction": "D IH0 S F AH1 NG K SH AH0 N",
  "days": "D EY1 Z",
  "sovereign": "S AA1 V R AH0 N",
  "abrasive": "AH0 B R EY1 S IH0 V",
  "inventing": "IH2 N V EH1 N T IH0 NG",
  "run": "R AH1 N",
  "skilled": "S K IH1 L D",
  "amusing": "AH0 M Y UW1 Z IH0 NG",
  "seeking": "S IY1 K IH0 NG",
  "consideration": "K AH0 N S IH2 D ER0 EY1 SH AH0 N",
  "bested": "B EH1 S T IH0 D",
  "left": "L EH1 F T",
  "enlightenment": "EH2 N L AY1 T AH0 N M AH0 N T",
  "traps": "T R AE1 P S",
  "ideation": "AY2 D IY0 EY1 SH AH0 N",
  "advance": "AH0 D V AE1 N S",
  "night": "N AY1 T",
  "sheep": "SH IY1 P",
  "invested": "IH2 N V EH1 S T AH0 D",
  "understated": "AH1 N D ER0 S T EY2 T IH0 D",
  "recollection": "R EH2 K AH0 L EH1 K SH AH0 N",
  "gets": "G EH1 T S",
  "output": "AW1 T P UH2 T",
  "alert": "AH0 L ER1 T",
  "twisted": "T W IH1 S T IH0 D",
  "themes": "TH IY1 M Z",
  "network": "N EH1 T W ER2 K",
  "catching": "K AE1 CH IH0 NG",
  "similar": "S IH1 M AH0 L ER0",
  "bleeding": "B L IY1 D IH0 NG",
  "connected": "K AH0 N EH1 K T IH0 D",
  "banal": "B AH0 N AA1 L",
  "mystery": "M IH1 S T ER0 IY0",
  "wo": "W OW1",
  "egregious": "IH0 G R IY1 JH AH0 S",
  "solve": "S AA1 L V",
  "much": "M AH1 CH",
  "threads": "TH R EH1 D Z",
  "weak": "W IY1 K",
  "height": "HH AY1 T",
  "fantasy": "F AE1 N T AH0 S IY0",
  "grin": "G R IH1 N",
  "pure": "P Y UH1 R",
  "well": "W EH1 L",
  "greater": "G R EY1 T ER0",
  "ghost": "G OW1 S T",
  "rents": "R EH1 N T S",
  "dispell": "D IH0 S P EH1 L",
  "folks": "F OW1 K S",
  "danger": "D EY1 N JH ER0",
  "limbo": "L IH1 M B OW0",
  "engagement": "EH0 N G EY1 JH M AH0 N T",
  "exist": "IH0 G Z IH1 S T",
  "mines": "M AY1 N Z",
  "yangtze": "Y AE1 NG K T S IY1",
  "outlandish": "AW0 T L AE1 N D IH0 SH",
  "merge": "M ER1 JH",
  "endorsed": "EH0 N D AO1 R S T",
  "rotund": "R OW0 T AH1 N D",
  "delusions": "D IH0 L UW1 ZH AH0 N Z",
  "digging": "D IH1 G IH0 NG",
  "kicking": "K IH1 K IH0 NG",
  "flashed": "F L AE1 SH T",
  "fact": "F AE1 K T",
  "mania": "M EY1 N IY0 AH0",
  "beats": "B IY1 T S",
  "till": "T IH1 L",
  "jaws": "JH AO1 Z",
  "blade": "B L EY1 D",
  "colonel": "K ER1 N AH0 L",
  "breaks": "B R EY1 K S",
  "mad": "M AE1 D",
  "defeat": "D IH0 F IY1 T",
  "reaches": "R IY1 CH AH0 Z",
  "chronological": "K R AA2 N AH0 L AA1 JH IH0 K AH0 L",
  "derision": "D ER0 IH1 ZH AH0 N",
  "former": "F AO1 R M ER0",
  "nuisance": "N UW1 S AH0 N S",
  "bright": "B R AY1 T",
  "learns": "L ER1 N Z",
  "noose": "N UW1 S",
  "integrated": "IH1 N T AH0 G R EY2 T AH0 D",
  "slipping": "S L IH1 P IH0 NG",
  "innovation": "IH2 N AH0 V EY1 SH AH0 N",
  "threatened": "TH R EH1 T AH0 N D",
  "take": "T EY1 K",
  "chasin": "CH AE1 S IH0 N",
  "never": "N EH1 V ER0",
  "drunk": "D R AH1 NG K",
  "shifted": "SH IH1 F T IH0 D",
  "conserve": "K AH0 N S ER1 V",
  "keep": "K IY1 P",
  "obscenities": "AA0 B S EH1 N IH0 T IY0 Z",
  "degradation": "D EH2 G R AH0 D EY1 SH AH0 N",
  "wisp": "W IH1 S P",
  "objective": "AH0 B JH EH1 K T IH0 V",
  "teeth": "T IY1 TH",
  "context": "K AA1 N T EH0 K S T",
  "layers": "L EY1 ER0 Z",
  "ordinance": "AO1 R D AH0 N AH0 N S",
  "paranoia": "P EH2 R AH0 N OY1 AH0",
  "often": "AO1 F T AH0 N",
  "better": "B EH1 T ER0",
  "alleles": "AH0 L EH1 L IY0 Z",
  "cured": "K Y UH1 R D",
  "outta": "UW1 T AH0",
  "small": "S M AO1 L",
  "block": "B L AA1 K",
  "alters": "AO1 L T ER0 Z",
  "strategist": "S T R AE1 T IH0 JH IH0 S T",
  "captivity": "K AE0 P T IH1 V AH0 T IY0",
  "simulation": "S IH2 M Y AH0 L EY1 SH AH0 N",
  "contending": "K AH0 N T EH1 N D IH0 NG",
  "places": "P L EY1 S AH0 Z",
  "wrong": "R AO1 NG",
  "insistent": "IH2 N S IH1 S T AH0 N T",
  "crafted": "K R AE1 F T IH0 D",
  "invest": "IH2 N V EH1 S T",
  "hunt": "HH AH1 N T",
  "alright": "AO2 L R AY1 T",
  "broke": "B R OW1 K",
  "cognizance": "K AA1 G N AH0 Z AH0 N S",
  "planets": "P L AE1 N AH0 T S",
  "cliff": "K L IH1 F",
  "minds": "M AY1 N D Z",
  "short": "SH AO1 R T",
  "tapestry": "T AE1 P AH0 S T R IY0",
  "apostle": "AH0 P AO1 S AH0 L",
  "party": "P AA1 R T IY0",
  "function": "F AH1 NG K SH AH0 N",
  "enlist": "EH2 N L IH1 S T",
  "profit": "P R AA1 F AH0 T",
  "eternal": "IH0 T ER1 N AH0 L",
  "dope": "D OW1 P",
  "starin": "S T AE1 R IH0 N",
  "limit": "L IH1 M AH0 T",
  "glimpses": "G L IH1 M P S IH0 Z",
  "impact": "IH2 M P AE1 K T",
  "king": "K IH1 NG",
  "seldom": "S EH1 L D AH0 M",
  "change": "CH EY1 N JH",
  "havoc": "HH AE1 V AH0 K",
  "animals": "AE1 N AH0 M AH0 L Z",
  "instructions": "IH2 N S T R AH1 K SH AH0 N Z",
  "conceded": "K AH0 N S IY1 D IH0 D",
  "wheel": "W IY1 L",
  "phases": "F EY1 Z AH0 Z",
  "continuum": "K AH0 N T IH1 N Y UW0 AH0 M",
  "passive": "P AE1 S IH0 V",
  "cataclysm": "K AE1 T AH0 K L IH2 S AH0 M",
  "motives": "M OW1 T IH0 V Z",
  "guard": "G AA1 R D",
  "thwarted": "TH W AO1 R T IH0 D",
  "proclivities": "P R OW0 K L IH1 V AH0 T IY0 Z",
  "forget": "F ER0 G EH1 T",
  "inquisition": "IH2 N K W AH0 Z IH1 SH AH0 N",
  "fear": "F IH1 R",
  "transcends": "T R AE0 N S EH1 N D Z",
  "captain": "K AE1 P T AH0 N",
  "please": "P L IY1 Z",
  "victims": "V IH1 K T IH0 M Z",
  "realities": "R IY2 AE1 L AH0 T IY2 Z",
  "engulfing": "IH0 N G AH1 L F IH0 NG",
  "ire": "AY1 R",
  "contention": "K AH0 N T EH1 N SH AH0 N",
  "specter": "S P EH1 K T ER0",
  "operator": "AA1 P ER0 EY2 T ER0",
  "cyclone": "S IH0 K L OW1 N",
  "bends": "B EH1 N D Z",
  "flash": "F L AE1 SH",
  "price": "P R AY1 S",
  "amiss": "AH0 M IH1 S",
  "shatter": "SH AE1 T ER0",
  "throat": "TH R OW1 T",
  "commitments": "K AH0 M IH1 T M AH0 N T S",
  "ignorant": "IH1 G N ER0 AH0 N T",
  "limits": "L IH1 M AH0 T S",
  "lightning": "L AY1 T N IH0 NG",
  "incompatible": "IH2 N K AH0 M P AE1 T AH0 B AH0 L",
  "remains": "R IH0 M EY1 N Z",
  "medicine": "M EH1 D AH0 S AH0 N",
  "patron": "P EY1 T R AH0 N",
  "within": "W IH0 DH IH1 N",
  "taking": "T EY1 K IH0 NG",
  "inert": "IH2 N ER1 T",
  "light": "L AY1 T",
  "alarms": "AH0 L AA1 R M Z",
  "quelled": "K W EH1 L D",
  "imminent": "IH1 M AH0 N AH0 N T",
  "lead": "L EH1 D",
  "received": "R AH0 S IY1 V D",
  "tempt": "T EH1 M P T",
  "armstrong": "AA1 R M S T R AA2 NG",
  "break": "B R EY1 K",
  "permanent": "P ER1 M AA0 N EH2 N T",
  "trickster": "T R IH1 K S T ER0",
  "groan": "G R OW1 N",
  "tame": "T EY1 M",
  "mastery": "M AE1 S T ER0 IY0",
  "perfecting": "P ER0 F EH1 K T IH0 NG",
  "feast": "F IY1 S T",
  "kind": "K AY1 N D",
  "gavel": "G AE1 V AH0 L",
  "mood": "M UW1 D",
  "antithetical": "AE2 N T AH0 TH EH1 T IH0 K AH0 L",
  "abandon": "AH0 B AE1 N D AH0 N",
  "loose": "L UW1 S",
  "coin": "K OY1 N",
  "skin": "S K IH1 N",
  "upward": "AH1 P W ER0 D",
  "name": "N EY1 M",
  "sake": "S EY1 K",
  "drain": "D R EY1 N",
  "stooped": "S T UW1 P T",
  "convinced": "K AH0 N V IH1 N S T",
  "oracle": "AO1 R AH0 K AH0 L",
  "swan": "S W AA1 N",
  "patch": "P AE1 CH",
  "righteousness": "R AY1 CH AH0 S N AH0 S",
  "worn": "W AO1 R N",
  "dotted": "D AA1 T AH0 D",
  "falling": "F AA1 L IH0 NG",
  "perverse": "P ER0 V ER1 S",
  "education": "EH2 JH AH0 K EY1 SH AH0 N",
  "constructive": "K AH0 N S T R AH1 K T IH0 V",
  "assumed": "AH0 S UW1 M D",
  "accelerate": "AE0 K S EH1 L ER0 EY2 T",
  "inconsistencies": "IH2 NG K AA1 N S IH0 S T EH2 N S IY0 Z",
  "low": "L OW1",
  "commons": "K AA1 M AH0 N Z",
  "relations": "R IY0 L EY1 SH AH0 N Z",
  "entrenched": "EH0 N T R EH1 N CH T",
  "half": "HH AE1 F",
  "mean": "M IY1 N",
  "civility": "S AH0 V IH1 L AH0 T IY0",
  "hence": "HH EH1 N S",
  "fellowship": "F EH1 L OW0 SH IH2 P",
  "alliance": "AH0 L AY1 AH0 N S",
  "wordsmith": "W ER1 D S M IH2 TH",
  "forsaken": "F AO0 R S EY1 K AH0 N",
  "concentrate": "K AA1 N S AH0 N T R EY2 T",
  "house": "HH AW1 S",
  "trade": "T R EY1 D",
  "knowledge": "N AA1 L AH0 JH",
  "idolized": "AY1 D AH0 L AY2 Z D",
  "acts": "AE1 K T S",
  "otherwise": "AH1 DH ER0 W AY2 Z",
  "still": "S T IH1 L",
  "perches": "P ER1 CH IH0 Z",
  "corps": "K AO1 R",
  "come": "K AH1 M",
  "blend": "B L EH1 N D",
  "sentence": "S EH1 N T AH0 N S",
  "ate": "EY1 T",
  "lessons": "L EH1 S AH0 N Z",
  "gripping": "G R IH1 P IH0 NG",
  "glad": "G L AE1 D",
  "sausage": "S AO1 S AH0 JH",
  "lend": "L EH1 N D",
  "marks": "M AA1 R K S",
  "further": "F ER1 DH ER0",
  "curses": "K ER1 S IH0 Z",
  "quiet": "K W AY1 AH0 T",
  "statement": "S T EY1 T M AH0 N T",
  "stated": "S T EY1 T IH0 D",
  "permissions": "P ER0 M IH1 SH AH0 N Z",
  "vested": "V EH1 S T IH0 D",
  "anyway": "EH1 N IY0 W EY2",
  "assume": "AH0 S UW1 M",
  "conditioned": "K AH0 N D IH1 SH AH0 N D",
  "swell": "S W EH1 L",
  "prevalence": "P R EH1 V AH0 L AH0 N S",
  "evangelist": "IH0 V AE1 N JH AH0 L IH0 S T",
  "unprecedented": "AH0 N P R EH1 S IH0 D EH2 N T IH0 D",
  "consigned": "K AH0 N S AY1 N D",
  "styx": "S T IH1 K S",
  "immaculate": "IH2 M AE1 K Y UW0 L IH0 T",
  "grievance": "G R IY1 V AH0 N S",
  "end": "EH1 N D",
  "show": "SH OW1",
  "explicate": "EH1 K S P L AH0 K EY2 T",
  "planned": "P L AE1 N D",
  "stoked": "S T OW1 K T",
  "less": "L EH1 S",
  "rhyme": "R AY1 M",
  "clock": "K L AA1 K",
  "limitless": "L IH1 M AH0 T L AH0 S",
  "choose": "CH UW1 Z",
  "indications": "IH2 N D AH0 K EY1 SH AH0 N Z",
  "search": "S ER1 CH",
  "positive": "P AA1 Z AH0 T IH0 V",
  "grab": "G R AE1 B",
  "away": "AH0 W EY1",
  "excited": "IH0 K S AY1 T AH0 D",
  "vault": "V AO1 L T",
  "fade": "F EY1 D",
  "security": "S IH0 K Y UH1 R AH0 T IY0",
  "fast": "F AE1 S T",
  "hatred": "HH EY1 T R AH0 D",
  "volcanic": "V AA0 L K AE1 N IH0 K",
  "congruent": "K AO1 N G R UW0 EH2 N T",
  "happened": "HH AE1 P AH0 N D",
  "illusions": "IH2 L UW1 ZH AH0 N Z",
  "sigh": "S AY1",
  "bout": "B AW1 T",
  "effects": "IH0 F EH1 K T S",
  "rent": "R EH1 N T",
  "blast": "B L AE1 S T",
  "pets": "P EH1 T S",
  "zero": "Z IY1 R OW0",
  "today": "T AH0 D EY1",
  "hey": "HH EY1",
  "irrelevant": "IH2 R EH1 L AH0 V AH0 N T",
  "mastered": "M AE1 S T ER0 D",
  "prevent": "P R IH0 V EH1 N T",
  "relay": "R IY1 L EY2",
  "yeah": "Y AE1",
  "latchkey": "L AE1 CH K IY2",
  "missionary": "M IH1 SH AH0 N EH2 R IY0",
  "rhymes": "R AY1 M Z",
  "alerted": "AH0 L ER1 T IH0 D",
  "aura": "AO1 R AH0",
  "weave": "W IY1 V",
  "consciousness": "K AA1 N SH AH0 S N AH0 S",
  "present": "P R EH1 Z AH0 N T",
  "though": "DH OW1",
  "deflate": "D IH0 F L EY1 T",
  "pharmaceutical": "F AA2 R M AH0 S UW1 T IH0 K AH0 L",
  "offset": "AO0 F S EH1 T",
  "clear": "K L IH1 R",
  "deliberate": "D IH0 L IH1 B ER0 AH0 T",
  "strap": "S T R AE1 P",
  "dependencies": "D IH0 P EH1 N D AH0 N S IY0 Z",
  "fend": "F EH1 N D",
  "onward": "AO1 N W ER0 D",
  "afford": "AH0 F AO1 R D",
  "hijacked": "HH AY1 JH AE2 K T",
  "effect": "IH0 F EH1 K T",
  "built": "B IH1 L T",
  "vain": "V EY1 N",
  "reference": "R EH1 F ER0 AH0 N S",
  "day": "D EY1",
  "shine": "SH AY1 N",
  "wealth": "W EH1 L TH",
  "dwell": "D W EH1 L",
  "hollow": "HH AA1 L OW0",
  "contest": "K AA1 N T EH0 S T",
  "running": "R AH1 N IH0 NG",
  "style": "S T AY1 L",
  "concepts": "K AA1 N S EH0 P T S",
  "positions": "P AH0 Z IH1 SH AH0 N Z",
  "compliance": "K AH0 M P L AY1 AH0 N S",
  "poems": "P OW1 AH0 M Z",
  "utter": "AH1 T ER0",
  "letter": "L EH1 T ER0",
  "consolidated": "K AH0 N S AA1 L AH0 D EY2 T AH0 D",
  "kids": "K IH1 D Z",
  "covered": "K AH1 V ER0 D",
  "swords": "S AO1 R D Z",
  "interweave": "IH2 N T ER0 W IY1 V",
  "uproot": "AH0 P R UW1 T",
  "course": "K AO1 R S",
  "stature": "S T AE1 CH ER0",
  "skate": "S K EY1 T",
  "good": "G UH1 D",
  "effusive": "EH1 F Y UW0 S IH0 V",
  "free": "F R IY1",
  "love": "L AH1 V",
  "dissolved": "D IH0 Z AA1 L V D",
  "forgot": "F ER0 G AA1 T",
  "competes": "K AH0 M P IY1 T S",
  "parry": "P EH1 R IY0",
  "giggle": "G IH1 G AH0 L",
  "churches": "CH ER1 CH IH0 Z",
  "ideal": "AY0 D IY1 L",
  "brethren": "B R EH1 DH R AH0 N",
  "toll": "T OW1 L",
  "fortress": "F AO1 R T R AH0 S",
  "make": "M EY1 K",
  "poppies": "P AA1 P IY0 Z",
  "construct": "K AH0 N S T R AH1 K T",
  "comprised": "K AH0 M P R AY1 Z D",
  "manifested": "M AE1 N AH0 F EH2 S T AH0 D",
  "collective": "K AH0 L EH1 K T IH0 V",
  "grief": "G R IY1 F",
  "time": "T AY1 M",
  "supply": "S AH0 P L AY1",
  "manger": "M EY1 N JH ER0",
  "stable": "S T EY1 B AH0 L",
  "technocratic": "T EH2 K N AH0 K R AE1 T IH0 K",
  "back": "B AE1 K",
  "genocide": "JH EH1 N AH0 S AY2 D",
  "morsels": "M AO1 R S AH0 L Z",
  "surreal": "S ER0 IY1 L",
  "law": "L AO1",
  "along": "AH0 L AO1 NG",
  "fabric": "F AE1 B R IH0 K",
  "keen": "K IY1 N",
  "containment": "K AH0 N T EY1 N M AH0 N T",
  "resigned": "R IH0 Z AY1 N D",
  "unfortunate": "AH0 N F AO1 R CH AH0 N AH0 T",
  "maligned": "M AH0 L AY1 N D",
  "opinions": "AH0 P IH1 N Y AH0 N Z",
  "carousel": "K EH1 R AH0 S EH2 L",
  "promptly": "P R AA1 M P T L IY0",
  "upload": "AH1 P L OW2 D",
  "amidst": "AH0 M IH1 D S T",
  "tempered": "T EH1 M P ER0 D",
  "culture": "K AH1 L CH ER0",
  "erase": "IH0 R EY1 S",
  "god": "G AA1 D",
  "proceeds": "P R AH0 S IY1 D Z",
  "nigh": "N AY1",
  "match": "M AE1 CH",
  "tribulation": "T R IH2 B Y AH0 L EY1 SH AH0 N",
  "struggle": "S T R AH1 G AH0 L",
  "populations": "P AA2 P Y AH0 L EY1 SH AH0 N Z",
  "appeared": "AH0 P IH1 R D",
  "compounded": "K AH0 M P AW1 N D AH0 D",
  "past": "P AE1 S T",
  "work": "W ER1 K",
  "denied": "D IH0 N AY1 D",
  "beneath": "B IH0 N IY1 TH",
  "conviction": "K AH0 N V IH1 K SH AH0 N",
  "vigil": "V IH1 JH AH0 L",
  "find": "F AY1 N D",
  "thread": "TH R EH1 D",
  "eyes": "AY1 Z",
  "fixation": "F IH0 K S EY1 SH AH0 N",
  "laid": "L EY1 D",
  "malignant": "M AH0 L IH1 G N AH0 N T",
  "blips": "B L IH1 P S",
  "compromised": "K AA1 M P R AH0 M AY2 Z D",
  "reevaluating": "R IY0 IH0 V AE1 L Y UW0 EY2 T IH0 NG",
  "words": "W ER1 D Z",
  "persisted": "P ER0 S IH1 S T IH0 D",
  "asylum": "AH0 S AY1 L AH0 M",
  "thankful": "TH AE1 NG K F AH0 L",
  "define": "D IH0 F AY1 N",
  "erasing": "IH0 R EY1 S IH0 NG",
  "scale": "S K EY1 L",
  "perpetual": "P ER0 P EH1 CH UW0 AH0 L",
  "gait": "G EY1 T",
  "agriculture": "AE1 G R IH0 K AH2 L CH ER0",
  "prodigal": "P R AA1 D IH0 G AH0 L",
  "convene": "K AH0 N V IY1 N",
  "indebted": "IH2 N D EH1 T IH0 D",
  "urgent": "ER1 JH AH0 N T",
  "extremes": "IH0 K S T R IY1 M Z",
  "void": "V OY1 D",
  "granted": "G R AE1 N T AH0 D",
  "brighten": "B R AY1 T AH0 N",
  "infiltrate": "IH1 N F IH0 L T R EY2 T",
  "imprisoned": "IH2 M P R IH1 Z AH0 N D",
  "tell": "T EH1 L",
  "distractions": "D IH0 S T R AE1 K SH AH0 N Z",
  "kinda": "K IH1 N D AH0",
  "oral": "AO1 R AH0 L",
  "exponentially": "EH2 K S P OW0 N EH1 N SH AH0 L IY0",
  "piston": "P IH1 S T AH0 N",
  "float": "F L OW1 T",
  "imperfections": "IH2 M P ER0 F EH1 K SH AH0 N Z",
  "civil": "S IH1 V AH0 L",
  "thrive": "TH R AY1 V",
  "demons": "D IY1 M AH0 N Z",
  "wrench": "R EH1 N CH",
  "inherent": "IH2 N HH EH1 R AH0 N T",
  "instincts": "IH1 N S T IH0 NG K T S",
  "vigilante": "V IH2 JH AH0 L AE1 N T IY0",
  "perturbed": "P ER0 T ER1 B D",
  "single": "S IH1 NG G AH0 L",
  "insight": "IH1 N S AY2 T",
  "indiscretion": "IH2 N D IH0 S K R EH1 SH AH0 N",
  "pacifist": "P AE1 S IH0 F IH0 S T",
  "palms": "P AA1 M Z",
  "anxiously": "AE1 NG K SH AH0 S L IY0",
  "tenet": "T EH1 N AH0 T",
  "capable": "K EY1 P AH0 B AH0 L",
  "taps": "T AE1 P S",
  "status": "S T AE1 T AH0 S",
  "aim": "EY1 M",
  "heads": "HH EH1 D Z",
  "fuck": "F AH1 K",
  "knife": "N AY1 F",
  "complaint": "K AH0 M P L EY1 N T",
  "let": "L EH1 T",
  "tree": "T R IY1",
  "enforce": "EH0 N F AO1 R S",
  "correcting": "K ER0 EH1 K T IH0 NG",
  "smoke": "S M OW1 K",
  "recover": "R IH0 K AH1 V ER0",
  "unknowns": "AH0 N OW1 N Z",
  "struck": "S T R AH1 K",
  "reflection": "R AH0 F L EH1 K SH AH0 N",
  "lights": "L AY1 T S",
  "mammals": "M AE1 M AH0 L Z",
  "leaving": "L IY1 V IH0 NG",
  "joke": "JH OW1 K",
  "simulate": "S IH1 M Y AH0 L AH0 T",
  "highest": "HH AY1 AH0 S T",
  "distance": "D IH1 S T AH0 N S",
  "really": "R IH1 L IY0",
  "outcomes": "AW1 T K AH2 M Z",
  "ensues": "IH0 N S UW1 Z",
  "unveiled": "AH0 N V EY1 L D",
  "schema": "S K IY1 M AH0",
  "died": "D AY1 D",
  "sign": "S AY1 N",
  "rush": "R AH1 SH",
  "treason": "T R IY1 Z AH0 N",
  "temporary": "T EH1 M P ER0 EH2 R IY0",
  "leveraged": "L IY1 V ER0 IH0 JH D",
  "generations": "JH EH2 N ER0 EY1 SH AH0 N Z",
  "gold": "G OW1 L D",
  "via": "V AY1 AH0",
  "guiding": "G AY1 D IH0 NG",
  "next": "N EH1 K S T",
  "veins": "V EY1 N Z",
  "thousand": "TH AW1 Z AH0 N D",
  "curtains": "K ER1 T AH0 N Z",
  "poison": "P OY1 Z AH0 N",
  "hard": "HH AA1 R D",
  "designated": "D EH1 Z IH0 G N EY2 T IH0 D",
  "outside": "AW1 T S AY1 D",
  "visions": "V IH1 ZH AH0 N Z",
  "unnerved": "AH0 N N ER1 V D",
  "meditation": "M EH2 D AH0 T EY1 SH AH0 N",
  "line": "L AY1 N",
  "truer": "T R UW1 ER0",
  "enchanted": "EH0 N CH AE1 N T IH0 D",
  "immolation": "IH1 M AH0 L EY2 SH AH0 N",
  "contemplated": "K AA1 N T AH0 M P L EY2 T IH0 D",
  "ousted": "AW1 S T IH0 D",
  "inertia": "IH2 N ER1 SH AH0",
  "motivates": "M OW1 T AH0 V EY2 T S",
  "arrow": "AE1 R OW0",
  "cover": "K AH1 V ER0",
  "empirically": "EH0 M P IH1 R IH0 K AH0 L IY0",
  "vagrant": "V EY1 G R AH0 N T",
  "elephants": "EH1 L AH0 F AH0 N T S",
  "reply": "R IH0 P L AY1",
  "disintegrated": "D IH0 S IH1 N T AH0 G R EY2 T IH0 D",
  "inclined": "IH2 N K L AY1 N D",
  "proverbs": "P R AA1 V ER0 B Z",
  "subjective": "S AH0 B JH EH1 K T IH0 V",
  "mistake": "M IH0 S T EY1 K",
  "glean": "G L IY1 N",
  "despite": "D IH0 S P AY1 T",
  "consists": "K AH0 N S IH1 S T S",
  "dates": "D EY1 T S",
  "data": "D EY1 T AH0",
  "seal": "S IY1 L",
  "sustained": "S AH0 S T EY1 N D",
  "deck": "D EH1 K",
  "online": "AO1 N L AY2 N",
  "strength": "S T R EH1 NG K TH",
  "doctors": "D AA1 K T ER0 Z",
  "disconnection": "D IH2 S K AH0 N EH1 K SH AH0 N",
  "pains": "P EY1 N Z",
  "cast": "K AE1 S T",
  "anger": "AE1 NG G ER0",
  "crisis": "K R AY1 S AH0 S",
  "sit": "S IH1 T",
  "kings": "K IH1 NG Z",
  "diluted": "D AY0 L UW1 T AH0 D",
  "burdens": "B ER1 D AH0 N Z",
  "escape": "IH0 S K EY1 P",
  "laughing": "L AE1 F IH0 NG",
  "down": "D AW1 N",
  "floor": "F L AO1 R",
  "perfect": "P ER0 F EH1 K T",
  "dives": "D AY1 V Z",
  "scaffold": "S K AE1 F AH0 L D",
  "cells": "S EH1 L Z",
  "fat": "F AE1 T",
  "intent": "IH2 N T EH1 N T",
  "tension": "T EH1 N SH AH0 N",
  "persistent": "P ER0 S IH1 S T AH0 N T",
  "measure": "M EH1 ZH ER0",
  "insistence": "IH2 N S IH1 S T AH0 N S",
  "weeds": "W IY1 D Z",
  "swear": "S W EH1 R",
  "rarely": "R EH1 R L IY0",
  "haunts": "HH AO1 N T S",
  "pit": "P IH1 T",
  "laws": "L AO1 Z",
  "sky": "S K AY1",
  "concede": "K AH0 N S IY1 D",
  "dropping": "D R AA1 P IH0 NG",
  "place": "P L EY1 S",
  "inflamed": "IH0 N F L EY1 M D",
  "rift": "R IH1 F T",
  "monopolies": "M AH0 N AA1 P AH0 L IY0 Z",
  "supersede": "S UW2 P ER0 S IY1 D",
  "prophet": "P R AA1 F AH0 T",
  "predictive": "P R IH0 D IH1 K T IH0 V",
  "medicinal": "M AH0 D IH1 S AH0 N AH0 L",
  "metal": "M EH1 T AH0 L",
  "functions": "F AH1 NG K SH AH0 N Z",
  "view": "V Y UW1",
  "contact": "K AA1 N T AE2 K T",
  "brain": "B R EY1 N",
  "gates": "G EY1 T S",
  "favor": "F EY1 V ER0",
  "invariably": "IH2 N V EH1 R IY0 AH0 B L IY0",
  "health": "HH EH1 L TH",
  "framework": "F R EY1 M W ER2 K",
  "stop": "S T AA1 P",
  "eliminated": "IH0 L IH1 M AH0 N EY2 T AH0 D",
  "deluded": "D IH0 L UW1 D IH0 D",
  "obstacles": "AA1 B S T AH0 K AH0 L Z",
  "limitations": "L IH2 M IH0 T EY1 SH AH0 N Z",
  "nourish": "N ER1 IH0 SH",
  "progression": "P R AH0 G R EH1 SH AH0 N",
  "exists": "IH0 G Z IH1 S T S",
  "contaminant": "K AH0 N T AE1 M AH0 N AH0 N T",
  "abandoned": "AH0 B AE1 N D AH0 N D",
  "celerity": "S AH0 L EH1 R AH0 T IY0",
  "processed": "P R AA1 S EH0 S T",
  "substance": "S AH1 B S T AH0 N S",
  "golden": "G OW1 L D AH0 N",
  "aplenty": "AH0 P L EH1 N T IY0",
  "one": "W AH1 N",
  "like": "L AY1 K",
  "pocket": "P AA1 K AH0 T",
  "ontological": "AA2 N T AH0 L AA1 JH IH0 K AH0 L",
  "treasure": "T R EH1 ZH ER0",
  "envisioned": "EH0 N V IH1 ZH AH0 N D",
  "cross": "K R AO1 S",
  "decline": "D IH0 K L AY1 N",
  "heaven": "HH EH1 V AH0 N",
  "apes": "EY1 P S",
  "staring": "S T EH1 R IH0 NG",
  "traditions": "T R AH0 D IH1 SH AH0 N Z",
  "tormented": "T AO1 R M EH2 N T IH0 D",
  "lift": "L IH1 F T",
  "sort": "S AO1 R T",
  "cancer": "K AE1 N S ER0",
  "widespread": "W AY1 D S P R EH1 D",
  "blessings": "B L EH1 S IH0 NG Z",
  "chrome": "K R OW1 M",
  "arc": "AA1 R K",
  "heavens": "HH EH1 V AH0 N Z",
  "selective": "S AH0 L EH1 K T IH0 V",
  "inevitable": "IH2 N EH1 V AH0 T AH0 B AH0 L",
  "soothe": "S UW1 DH",
  "nowhere": "N OW1 W EH2 R",
  "absorbed": "AH0 B Z AO1 R B D",
  "basement": "B EY1 S M AH0 N T",
  "whims": "W IH1 M Z",
  "blood": "B L AH1 D",
  "summon": "S AH1 M AH0 N",
  "politicians": "P AA2 L AH0 T IH1 SH AH0 N Z",
  "problem": "P R AA1 B L AH0 M",
  "rampant": "R AE1 M P AH0 N T",
  "standard": "S T AE1 N D ER0 D",
  "contested": "K AH0 N T EH1 S T AH0 D",
  "secure": "S IH0 K Y UH1 R",
  "merging": "M ER1 JH IH0 NG",
  "nothin": "N AA1 TH IH0 N",
  "poke": "P OW1 K",
  "misery": "M IH1 Z ER0 IY0",
  "careful": "K EH1 R F AH0 L",
  "seized": "S IY1 Z D",
  "impressions": "IH2 M P R EH1 SH AH0 N Z",
  "clay": "K L EY1",
  "unity": "Y UW1 N IH0 T IY0",
  "ceilings": "S IY1 L IH0 NG Z",
  "lesson": "L EH1 S AH0 N",
  "instilled": "IH2 N S T IH1 L D",
  "ve": "V IY1",
  "unnecessary": "AH0 N N EH1 S AH0 S EH2 R IY0",
  "room": "R UW1 M",
  "goin": "G OY1 N",
  "courts": "K AO1 R T S",
  "hush": "HH AH1 SH",
  "combined": "K AH0 M B AY1 N D",
  "structures": "S T R AH1 K CH ER0 Z",
  "fashion": "F AE1 SH AH0 N",
  "genetically": "JH AH0 N EH1 T IH0 K L IY0",
  "struggles": "S T R AH1 G AH0 L Z",
  "sounds": "S AW1 N D Z",
  "admit": "AH0 D M IH1 T",
  "order": "AO1 R D ER0",
  "loving": "L AH1 V IH0 NG",
  "rebel": "R EH1 B AH0 L",
  "fun": "F AH1 N",
  "immeasurable": "IH2 M EH1 ZH ER0 AE2 B AH0 L",
  "latter": "L AE1 T ER0",
  "ready": "R EH1 D IY0",
  "levitation": "L EH2 V IH0 T EY1 SH AH0 N",
  "roam": "R OW1 M",
  "magician": "M AH0 JH IH1 SH AH0 N",
  "rendered": "R EH1 N D ER0 D",
  "scene": "S IY1 N",
  "conservative": "K AH0 N S ER1 V AH0 T IH0 V",
  "evening": "IY1 V N IH0 NG",
  "dig": "D IH1 G",
  "confusing": "K AH0 N F Y UW1 Z IH0 NG",
  "lucid": "L UW1 S IH0 D",
  "stops": "S T AA1 P S",
  "cake": "K EY1 K",
  "resign": "R IH0 Z AY1 N",
  "incite": "IH2 N S AY1 T",
  "tandem": "T AE1 N D AH0 M",
  "alms": "AA1 L M Z",
  "approaching": "AH0 P R OW1 CH IH0 NG",
  "endlessly": "EH1 N D L AH0 S L IY0",
  "arithmetic": "EH2 R IH0 TH M EH1 T IH0 K",
  "confined": "K AH0 N F AY1 N D",
  "raise": "R EY1 Z",
  "craft": "K R AE1 F T",
  "understand": "AH2 N D ER0 S T AE1 N D",
  "obsidian": "AH0 B S IH1 D IY0 AH0 N",
  "evidence": "EH1 V AH0 D AH0 N S",
  "origin": "AO1 R AH0 JH AH0 N",
  "attend": "AH0 T EH1 N D",
  "thickens": "TH IH1 K AH0 N Z",
  "chimps": "CH IH1 M P S",
  "purpose": "P ER1 P AH0 S",
  "yearning": "Y ER1 N IH0 NG",
  "raven": "R EY1 V AH0 N",
  "scam": "S K AE1 M",
  "stakes": "S T EY1 K S",
  "fuse": "F Y UW1 Z",
  "gloom": "G L UW1 M",
  "sealing": "S IY1 L IH0 NG",
  "hopes": "HH OW1 P S",
  "stage": "S T EY1 JH",
  "contentious": "K AH0 N T EH1 N SH AH0 S",
  "subject": "S AH0 B JH EH1 K T",
  "chance": "CH AE1 N S",
  "pensive": "P EH1 N S IH0 V",
  "na": "N AA1",
  "pavement": "P EY1 V M AH0 N T",
  "reach": "R IY1 CH",
  "grace": "G R EY1 S",
  "manufactured": "M AE2 N Y AH0 F AE1 K CH ER0 D",
  "choice": "CH OY1 S",
  "counteract": "K AW1 N T ER0 AE2 K T",
  "killing": "K IH1 L IH0 NG",
  "thy": "DH AY1",
  "visionary": "V IH1 ZH AH0 N EH2 R IY0",
  "praxis": "P R AE1 K S IH0 S",
  "catastrophe": "K AH0 T AE1 S T R AH0 F IY0",
  "ballistics": "B AH0 L IH1 S T IH0 K S",
  "nothings": "N AH1 TH IH0 NG Z",
  "meaningless": "M IY1 N IH0 NG L AH0 S",
  "stay": "S T EY1",
  "senses": "S EH1 N S IH0 Z",
  "continue": "K AH0 N T IH1 N Y UW0",
  "arrogance": "EH1 R AH0 G AH0 N S",
  "wasting": "W EY1 S T IH0 NG",
  "monsters": "M AA1 N S T ER0 Z",
  "revelations": "R EH2 V AH0 L EY1 SH AH0 N Z",
  "closer": "K L OW1 S ER0",
  "surgeon": "S ER1 JH AH0 N",
  "boys": "B OY1 Z",
  "shell": "SH EH1 L",
  "spires": "S P AY1 R Z",
  "equally": "IY1 K W AH0 L IY0",
  "tooth": "T UW1 TH",
  "suffice": "S AH0 F AY1 S",
  "unable": "AH0 N EY1 B AH0 L",
  "nuclei": "N UW1 K L IY0 AY2",
  "overloaded": "OW1 V ER0 L OW2 D IH0 D",
  "cravin": "K R EY1 V IH0 N",
  "cycles": "S AY1 K AH0 L Z",
  "synapse": "S IH1 N AE0 P S",
  "princess": "P R IH1 N S EH0 S",
  "policy": "P AA1 L AH0 S IY0",
  "cranium": "K R EY1 N IY2 AH0 M",
  "destruction": "D IH0 S T R AH1 K SH AH0 N",
  "steel": "S T IY1 L",
  "capture": "K AE1 P CH ER0",
  "lean": "L IY1 N",
  "rations": "R AE1 SH AH0 N Z",
  "defunct": "D IH0 F AH1 NG K T",
  "meet": "M IY1 T",
  "transfer": "T R AE0 N S F ER1",
  "ascertained": "AE2 S ER0 T EY1 N D",
  "demonstrated": "D EH1 M AH0 N S T R EY2 T AH0 D",
  "sensations": "S EH0 N S EY1 SH AH0 N Z",
  "expression": "IH0 K S P R EH1 SH AH0 N",
  "woes": "W OW1 Z",
  "perspective": "P ER0 S P EH1 K T IH0 V",
  "dog": "D AO1 G",
  "prime": "P R AY1 M",
  "chronicle": "K R AA1 N IH0 K AH0 L",
  "interlace": "IH2 N T ER0 L EY1 S",
  "chasm": "K AE1 Z AH0 M",
  "throughout": "TH R UW0 AW1 T",
  "tie": "T AY1",
  "bow": "B AW1",
  "simple": "S IH1 M P AH0 L",
  "elevation": "EH2 L AH0 V EY1 SH AH0 N",
  "untenable": "AH0 N T EH1 N AH0 B AH0 L",
  "verse": "V ER1 S",
  "head": "HH EH1 D",
  "send": "S EH1 N D",
  "sweat": "S W EH1 T",
  "arms": "AA1 R M Z",
  "court": "K AO1 R T",
  "ruckus": "R AH1 K AH0 S",
  "poor": "P UW1 R",
  "robots": "R OW1 B AA2 T S",
  "deflection": "D IH0 F L EH1 K SH AH0 N",
  "esoteric": "EH2 S AH0 T EH1 R IH0 K",
  "weight": "W EY1 T",
  "properly": "P R AA1 P ER0 L IY0",
  "distribution": "D IH2 S T R AH0 B Y UW1 SH AH0 N",
  "sentiment": "S EH1 N T AH0 M AH0 N T",
  "biological": "B AY2 AH0 L AA1 JH IH0 K AH0 L",
  "refined": "R AH0 F AY1 N D",
  "surface": "S ER1 F AH0 S",
  "hold": "HH OW1 L D"
};
